// src/constants/internalPortalData.js
// Sample data for Internal Spectra Portal

/**
 * Customer/Tenant Data
 */
export const customers = [
  {
    id: "cust_001",
    name: "Oberoi Hotels & Resorts",
    type: "Hotel",
    industry: "Hospitality",
    segment: "Enterprise",
    status: "active",
    contractStart: "2023-01-15",
    contractEnd: "2025-01-14",
    createdAt: "2023-01-15",
    accountManager: "Priya Sharma",
    supportTier: "Premium",
    licenseTier: "Enterprise",
    contactName: "Rajesh Kumar",
    contactEmail: "rajesh.kumar@oberoihotels.com",
    contactPhone: "+91 98765 43210",
    totalSites: 12,
    activeSites: 11,
    totalUsers: 2450,
    totalDevices: 3200,
    logo: null,
  },
  {
    id: "cust_002",
    name: "WeWork India",
    type: "Co-Working",
    industry: "Real Estate",
    segment: "Enterprise",
    status: "active",
    contractStart: "2022-06-01",
    contractEnd: "2024-05-31",
    createdAt: "2022-06-01",
    accountManager: "Rahul Mehta",
    supportTier: "Premium",
    licenseTier: "Enterprise",
    contactName: "Amit Verma",
    contactEmail: "amit.verma@wework.co.in",
    contactPhone: "+91 98123 45678",
    totalSites: 28,
    activeSites: 28,
    totalUsers: 15200,
    totalDevices: 8500,
    logo: null,
  },
  {
    id: "cust_003",
    name: "Nestaway Technologies",
    type: "Co-Living",
    industry: "Real Estate",
    segment: "SMB",
    status: "active",
    contractStart: "2023-03-10",
    contractEnd: "2024-03-09",
    createdAt: "2023-03-10",
    accountManager: "Anita Desai",
    supportTier: "Standard",
    licenseTier: "Professional",
    contactName: "Sneha Patel",
    contactEmail: "sneha.patel@nestaway.com",
    contactPhone: "+91 99876 54321",
    totalSites: 45,
    activeSites: 42,
    totalUsers: 8900,
    totalDevices: 4200,
    logo: null,
  },
  {
    id: "cust_004",
    name: "Zolo Stays",
    type: "PG",
    industry: "Hospitality",
    segment: "SMB",
    status: "active",
    contractStart: "2023-07-20",
    contractEnd: "2024-07-19",
    createdAt: "2023-07-20",
    accountManager: "Vikram Singh",
    supportTier: "Standard",
    licenseTier: "Professional",
    contactName: "Nikhil Reddy",
    contactEmail: "nikhil.reddy@zolostays.com",
    contactPhone: "+91 97654 32109",
    totalSites: 120,
    activeSites: 115,
    totalUsers: 24000,
    totalDevices: 12000,
    logo: null,
  },
  {
    id: "cust_005",
    name: "ITC Hotels",
    type: "Hotel",
    industry: "Hospitality",
    segment: "Enterprise",
    status: "active",
    contractStart: "2022-09-01",
    contractEnd: "2025-08-31",
    createdAt: "2022-09-01",
    accountManager: "Priya Sharma",
    supportTier: "Premium",
    licenseTier: "Enterprise",
    contactName: "Suresh Menon",
    contactEmail: "suresh.menon@itchotels.in",
    contactPhone: "+91 98234 56789",
    totalSites: 8,
    activeSites: 8,
    totalUsers: 1800,
    totalDevices: 2400,
    logo: null,
  },
  {
    id: "cust_006",
    name: "Awfis Space Solutions",
    type: "Co-Working",
    industry: "Real Estate",
    segment: "Enterprise",
    status: "active",
    contractStart: "2023-02-15",
    contractEnd: "2025-02-14",
    createdAt: "2023-02-15",
    accountManager: "Rahul Mehta",
    supportTier: "Premium",
    licenseTier: "Enterprise",
    contactName: "Kavita Sharma",
    contactEmail: "kavita.sharma@awfis.com",
    contactPhone: "+91 98345 67890",
    totalSites: 35,
    activeSites: 33,
    totalUsers: 12500,
    totalDevices: 7800,
    logo: null,
  },
  {
    id: "cust_007",
    name: "Stanza Living",
    type: "Co-Living",
    industry: "Real Estate",
    segment: "Enterprise",
    status: "active",
    contractStart: "2023-04-01",
    contractEnd: "2025-03-31",
    createdAt: "2023-04-01",
    accountManager: "Anita Desai",
    supportTier: "Premium",
    licenseTier: "Enterprise",
    contactName: "Deepak Jain",
    contactEmail: "deepak.jain@stanzaliving.com",
    contactPhone: "+91 97456 78901",
    totalSites: 85,
    activeSites: 82,
    totalUsers: 18500,
    totalDevices: 9200,
    logo: null,
  },
  {
    id: "cust_008",
    name: "OYO Rooms",
    type: "Hotel",
    industry: "Hospitality",
    segment: "Enterprise",
    status: "inactive",
    contractStart: "2024-01-01",
    contractEnd: "2026-12-31",
    createdAt: "2024-01-01",
    accountManager: "Vikram Singh",
    supportTier: "Premium",
    licenseTier: "Enterprise",
    contactName: "Rohit Kapoor",
    contactEmail: "rohit.kapoor@oyorooms.com",
    contactPhone: "+91 96567 89012",
    totalSites: 250,
    activeSites: 180,
    totalUsers: 45000,
    totalDevices: 28000,
    logo: null,
  },
  {
    id: "cust_009",
    name: "Treebo Hotels",
    type: "Hotel",
    industry: "Hospitality",
    segment: "SMB",
    status: "active",
    contractStart: "2023-08-15",
    contractEnd: "2024-08-14",
    createdAt: "2023-08-15",
    accountManager: "Priya Sharma",
    supportTier: "Standard",
    licenseTier: "Professional",
    contactName: "Meera Nair",
    contactEmail: "meera.nair@treebo.com",
    contactPhone: "+91 95678 90123",
    totalSites: 65,
    activeSites: 58,
    totalUsers: 3200,
    totalDevices: 4500,
    logo: null,
  },
  {
    id: "cust_010",
    name: "Tata Consultancy Services",
    type: "Enterprise",
    industry: "IT Services",
    segment: "Enterprise",
    status: "active",
    contractStart: "2023-01-01",
    contractEnd: "2025-12-31",
    createdAt: "2023-01-01",
    accountManager: "Priya Sharma",
    supportTier: "Premium",
    licenseTier: "Enterprise",
    contactName: "Venkat Raghavan",
    contactEmail: "venkat.raghavan@tcs.com",
    contactPhone: "+91 98765 43300",
    totalSites: 45,
    activeSites: 42,
    totalUsers: 85000,
    totalDevices: 52000,
    logo: null,
  },
  {
    id: "cust_011",
    name: "Infosys Limited",
    type: "Office",
    industry: "IT Services",
    segment: "Enterprise",
    status: "active",
    contractStart: "2023-03-01",
    contractEnd: "2025-06-30",
    createdAt: "2023-03-01",
    accountManager: "Rahul Mehta",
    supportTier: "Premium",
    licenseTier: "Enterprise",
    contactName: "Priya Menon",
    contactEmail: "priya.menon@infosys.com",
    contactPhone: "+91 98765 43310",
    totalSites: 28,
    activeSites: 26,
    totalUsers: 42000,
    totalDevices: 28000,
    logo: null,
  },
  {
    id: "cust_012",
    name: "Delhi Municipal Corporation",
    type: "Miscellaneous",
    industry: "Government",
    segment: "Government",
    status: "active",
    contractStart: "2023-09-01",
    contractEnd: "2024-09-30",
    createdAt: "2023-09-01",
    accountManager: "Vikram Singh",
    supportTier: "Standard",
    licenseTier: "Professional",
    contactName: "Rakesh Sharma",
    contactEmail: "rakesh.sharma@dmc.gov.in",
    contactPhone: "+91 98765 43320",
    totalSites: 12,
    activeSites: 10,
    totalUsers: 5500,
    totalDevices: 3200,
    logo: null,
  },
];

/**
 * Site Data with detailed metrics
 */
export const sites = [
  // Oberoi Hotels Sites
  {
    id: "site_001",
    customerId: "cust_001",
    customerName: "Oberoi Hotels & Resorts",
    name: "The Oberoi, Mumbai",
    city: "Mumbai",
    state: "Maharashtra",
    region: "West",
    type: "Hotel",
    status: "online",
    deploymentDate: "2023-02-01",
    lastSeen: "2024-01-15T10:30:00",
    totalUsers: 320,
    activeUsers: 285,
    totalDevices: 420,
    onlineDevices: 415,
    bandwidthUsage: 850, // Mbps
    bandwidthLimit: 1000,
    storageUsed: 45, // GB
    storageLimit: 100,
    activeConnections: 892,
    dailyDataTransfer: 2.4, // TB
    uptime: 99.98,
    alerts: 2,
    criticalAlerts: 0,
    licenseTier: "Premium",
    licenseExpiry: "2025-01-14",
    primaryContact: "Amit Khanna",
    primaryEmail: "amit.khanna@oberoihotels.com",
    primaryPhone: "+91 98765 43210",
    guestAccessEnabled: true,
    authenticationConfig: {
      roomGuests: ['lastname_roomnumber', 'otp_rmn', 'wpa2_psk'],
      guests: ['otp_mn', 'coupon_voucher', 'event_code'],
      conferenceRooms: ['event_code', 'sponsored_authority'],
      devices: ['mac_auth', 'wpa2_psk'],
      staff: ['username_password', 'wpa2_psk']
    },
    infrastructure: {
      apVendor: "ruckus",
      apModel: "R750",
      deployedApCount: 85,
      liveApCount: 83,
      indoorApCount: 75,
      outdoorApCount: 10,
      poeSwitchVendor: "edgecore",
      poeSwitchCount: 12,
      livePoeSwitchCount: 12,
      totalPoePorts: 288,
      usedPoePorts: 195,
      nasCount: 2,
      firewallCount: 2,
      upsCount: 4,
    },
  },
  {
    id: "site_002",
    customerId: "cust_001",
    customerName: "Oberoi Hotels & Resorts",
    name: "The Oberoi, Delhi",
    city: "New Delhi",
    state: "Delhi",
    region: "North",
    type: "Hotel",
    status: "online",
    deploymentDate: "2023-02-15",
    lastSeen: "2024-01-15T10:28:00",
    totalUsers: 280,
    activeUsers: 245,
    totalDevices: 380,
    onlineDevices: 375,
    bandwidthUsage: 720,
    bandwidthLimit: 1000,
    storageUsed: 38,
    storageLimit: 100,
    activeConnections: 756,
    dailyDataTransfer: 2.1,
    uptime: 99.95,
    alerts: 1,
    criticalAlerts: 0,
    licenseTier: "Premium",
    licenseExpiry: "2025-01-14",
    primaryContact: "Neha Gupta",
    primaryEmail: "neha.gupta@oberoihotels.com",
    primaryPhone: "+91 98765 43211",
    guestAccessEnabled: true,
    authenticationConfig: {
      roomGuests: ['lastname_roomnumber', 'otp_rmn', 'wpa2_psk'],
      guests: ['otp_mn', 'coupon_voucher'],
      conferenceRooms: ['event_code', 'sponsored_authority'],
      devices: ['mac_auth', 'wpa2_psk'],
      staff: ['username_password', 'wpa2_psk']
    },
    infrastructure: {
      apVendor: "ruckus",
      apModel: "R650",
      deployedApCount: 72,
      liveApCount: 71,
      indoorApCount: 65,
      outdoorApCount: 7,
      poeSwitchVendor: "edgecore",
      poeSwitchCount: 10,
      livePoeSwitchCount: 10,
      totalPoePorts: 240,
      usedPoePorts: 168,
      nasCount: 2,
      firewallCount: 2,
      upsCount: 3,
    },
  },
  {
    id: "site_003",
    customerId: "cust_001",
    customerName: "Oberoi Hotels & Resorts",
    name: "The Oberoi, Bangalore",
    city: "Bangalore",
    state: "Karnataka",
    region: "South",
    type: "Hotel",
    status: "degraded",
    deploymentDate: "2023-03-01",
    lastSeen: "2024-01-15T10:25:00",
    totalUsers: 250,
    activeUsers: 180,
    totalDevices: 320,
    onlineDevices: 280,
    bandwidthUsage: 450,
    bandwidthLimit: 1000,
    storageUsed: 42,
    storageLimit: 100,
    activeConnections: 425,
    dailyDataTransfer: 1.5,
    uptime: 97.50,
    alerts: 8,
    criticalAlerts: 2,
    licenseTier: "Premium",
    licenseExpiry: "2025-01-14",
    primaryContact: "Rajesh Kumar",
    primaryEmail: "rajesh.kumar@oberoihotels.com",
    primaryPhone: "+91 98765 43212",
    guestAccessEnabled: false,
    authenticationConfig: {
      roomGuests: ['lastname_roomnumber', 'wpa2_psk'],
      guests: ['otp_mn'],
      conferenceRooms: ['event_code'],
      devices: ['mac_auth', 'wpa2_psk'],
      staff: ['username_password', 'wpa2_psk']
    },
    infrastructure: {
      apVendor: "edgecore",
      apModel: "EAP101",
      deployedApCount: 65,
      liveApCount: 58,
      indoorApCount: 55,
      outdoorApCount: 10,
      poeSwitchVendor: "tp_link",
      poeSwitchCount: 8,
      livePoeSwitchCount: 7,
      totalPoePorts: 192,
      usedPoePorts: 142,
      nasCount: 2,
      firewallCount: 1,
      upsCount: 3,
    },
  },
  // WeWork Sites
  {
    id: "site_004",
    customerId: "cust_002",
    customerName: "WeWork India",
    name: "WeWork Galaxy, Bangalore",
    city: "Bangalore",
    state: "Karnataka",
    region: "South",
    type: "Co-Working",
    status: "online",
    deploymentDate: "2022-06-15",
    lastSeen: "2024-01-15T10:30:00",
    totalUsers: 850,
    activeUsers: 720,
    totalDevices: 520,
    onlineDevices: 515,
    bandwidthUsage: 1800,
    bandwidthLimit: 2000,
    storageUsed: 85,
    storageLimit: 200,
    activeConnections: 1450,
    dailyDataTransfer: 5.2,
    uptime: 99.99,
    alerts: 0,
    criticalAlerts: 0,
    licenseTier: "Enterprise",
    licenseExpiry: "2024-05-31",
    primaryContact: "Sneha Reddy",
    primaryEmail: "sneha.reddy@wework.co.in",
    primaryPhone: "+91 98765 43220",
    guestAccessEnabled: true,
    authenticationConfig: {
      members: ['username_password', 'member_id_password', 'otp_rmn', 'wpa2_psk'],
      guests: ['otp_mn', 'sponsored_employee', 'coupon_voucher'],
      conferenceRooms: ['event_code', 'sponsored_authority'],
      devices: ['mac_auth', 'wpa2_psk']
    },
    infrastructure: {
      apVendor: "tp_link",
      apModel: "EAP670",
      deployedApCount: 120,
      liveApCount: 120,
      indoorApCount: 110,
      outdoorApCount: 10,
      poeSwitchVendor: "edgecore",
      poeSwitchCount: 16,
      livePoeSwitchCount: 16,
      totalPoePorts: 384,
      usedPoePorts: 285,
      nasCount: 3,
      firewallCount: 2,
      upsCount: 6,
    },
  },
  {
    id: "site_005",
    customerId: "cust_002",
    customerName: "WeWork India",
    name: "WeWork BKC, Mumbai",
    city: "Mumbai",
    state: "Maharashtra",
    region: "West",
    type: "Co-Working",
    status: "online",
    deploymentDate: "2022-07-01",
    lastSeen: "2024-01-15T10:29:00",
    totalUsers: 1200,
    activeUsers: 980,
    totalDevices: 680,
    onlineDevices: 675,
    bandwidthUsage: 2200,
    bandwidthLimit: 2500,
    storageUsed: 120,
    storageLimit: 250,
    activeConnections: 2100,
    dailyDataTransfer: 7.8,
    uptime: 99.97,
    alerts: 1,
    criticalAlerts: 0,
    licenseTier: "Enterprise",
    licenseExpiry: "2024-05-31",
    primaryContact: "Arjun Patel",
    primaryEmail: "arjun.patel@wework.co.in",
    primaryPhone: "+91 98765 43221",
    guestAccessEnabled: true,
    authenticationConfig: {
      members: ['username_password', 'member_id_password', 'otp_rmn', 'wpa2_psk'],
      guests: ['otp_mn', 'sponsored_employee', 'coupon_voucher'],
      conferenceRooms: ['event_code', 'sponsored_authority'],
      devices: ['mac_auth', 'wpa2_psk']
    },
    infrastructure: {
      apVendor: "ruckus",
      apModel: "R850",
      deployedApCount: 150,
      liveApCount: 148,
      indoorApCount: 135,
      outdoorApCount: 15,
      poeSwitchVendor: "edgecore",
      poeSwitchCount: 20,
      livePoeSwitchCount: 20,
      totalPoePorts: 480,
      usedPoePorts: 365,
      nasCount: 4,
      firewallCount: 2,
      upsCount: 8,
    },
  },
  // Zolo Stays Sites
  {
    id: "site_006",
    customerId: "cust_004",
    customerName: "Zolo Stays",
    name: "Zolo Crown, Koramangala",
    city: "Bangalore",
    state: "Karnataka",
    region: "South",
    type: "PG",
    status: "online",
    deploymentDate: "2023-08-01",
    lastSeen: "2024-01-15T10:30:00",
    totalUsers: 180,
    activeUsers: 165,
    totalDevices: 95,
    onlineDevices: 92,
    bandwidthUsage: 280,
    bandwidthLimit: 500,
    storageUsed: 15,
    storageLimit: 50,
    activeConnections: 320,
    dailyDataTransfer: 0.8,
    uptime: 99.85,
    alerts: 1,
    criticalAlerts: 0,
    licenseTier: "Standard",
    licenseExpiry: "2024-07-19",
    primaryContact: "Kavitha Nair",
    primaryEmail: "kavitha@zolostays.com",
    primaryPhone: "+91 98765 43230",
    guestAccessEnabled: false,
    authenticationConfig: {
      residents: ['username_password', 'otp_rmn', 'wpa2_psk'],
      devices: ['mac_auth', 'wpa2_psk']
    },
    infrastructure: {
      apVendor: "tp_link",
      apModel: "EAP660 HD",
      deployedApCount: 18,
      liveApCount: 17,
      indoorApCount: 16,
      outdoorApCount: 2,
      poeSwitchVendor: "tp_link",
      poeSwitchCount: 3,
      livePoeSwitchCount: 3,
      totalPoePorts: 72,
      usedPoePorts: 45,
      nasCount: 1,
      firewallCount: 1,
      upsCount: 2,
    },
  },
  {
    id: "site_007",
    customerId: "cust_004",
    customerName: "Zolo Stays",
    name: "Zolo Starter, HSR Layout",
    city: "Bangalore",
    state: "Karnataka",
    region: "South",
    type: "PG",
    status: "offline",
    deploymentDate: "2023-08-15",
    lastSeen: "2024-01-14T22:15:00",
    totalUsers: 120,
    activeUsers: 0,
    totalDevices: 65,
    onlineDevices: 0,
    bandwidthUsage: 0,
    bandwidthLimit: 300,
    storageUsed: 8,
    storageLimit: 30,
    activeConnections: 0,
    dailyDataTransfer: 0,
    uptime: 85.20,
    alerts: 5,
    criticalAlerts: 3,
    licenseTier: "Standard",
    licenseExpiry: "2024-07-19",
    primaryContact: "Suresh Kumar",
    primaryEmail: "suresh@zolostays.com",
    primaryPhone: "+91 98765 43231",
    guestAccessEnabled: false,
    authenticationConfig: {
      residents: ['username_password', 'otp_rmn', 'wpa2_psk'],
      devices: ['mac_auth', 'wpa2_psk']
    },
    infrastructure: {
      apVendor: "edgecore",
      apModel: "EAP102",
      deployedApCount: 12,
      liveApCount: 0,
      indoorApCount: 10,
      outdoorApCount: 2,
      poeSwitchVendor: "tp_link",
      poeSwitchCount: 2,
      livePoeSwitchCount: 0,
      totalPoePorts: 48,
      usedPoePorts: 28,
      nasCount: 1,
      firewallCount: 1,
      upsCount: 1,
    },
  },
  // Stanza Living Sites
  {
    id: "site_008",
    customerId: "cust_007",
    customerName: "Stanza Living",
    name: "Stanza Living Madrid",
    city: "Pune",
    state: "Maharashtra",
    region: "West",
    type: "Co-Living",
    status: "online",
    deploymentDate: "2023-04-15",
    lastSeen: "2024-01-15T10:30:00",
    totalUsers: 350,
    activeUsers: 310,
    totalDevices: 180,
    onlineDevices: 178,
    bandwidthUsage: 520,
    bandwidthLimit: 800,
    storageUsed: 28,
    storageLimit: 80,
    activeConnections: 580,
    dailyDataTransfer: 1.6,
    uptime: 99.92,
    alerts: 0,
    criticalAlerts: 0,
    licenseTier: "Premium",
    licenseExpiry: "2025-03-31",
    primaryContact: "Deepak Joshi",
    primaryEmail: "deepak.joshi@stanzaliving.com",
    primaryPhone: "+91 98765 43240",
    guestAccessEnabled: true,
    authenticationConfig: {
      residents: ['username_password', 'otp_rmn', 'otp_mn', 'wpa2_psk'],
      guests: ['otp_mn', 'sponsored_employee', 'voucher_auto_account'],
      devices: ['mac_auth', 'wpa2_psk']
    },
    infrastructure: {
      apVendor: "ruckus",
      apModel: "R650",
      deployedApCount: 42,
      liveApCount: 42,
      indoorApCount: 38,
      outdoorApCount: 4,
      poeSwitchVendor: "edgecore",
      poeSwitchCount: 6,
      livePoeSwitchCount: 6,
      totalPoePorts: 144,
      usedPoePorts: 98,
      nasCount: 2,
      firewallCount: 1,
      upsCount: 3,
    },
  },
  {
    id: "site_009",
    customerId: "cust_007",
    customerName: "Stanza Living",
    name: "Stanza Living Florence",
    city: "Hyderabad",
    state: "Telangana",
    region: "South",
    type: "Co-Living",
    status: "online",
    deploymentDate: "2023-05-01",
    lastSeen: "2024-01-15T10:28:00",
    totalUsers: 280,
    activeUsers: 255,
    totalDevices: 145,
    onlineDevices: 142,
    bandwidthUsage: 420,
    bandwidthLimit: 600,
    storageUsed: 22,
    storageLimit: 60,
    activeConnections: 485,
    dailyDataTransfer: 1.3,
    uptime: 99.88,
    alerts: 2,
    criticalAlerts: 0,
    licenseTier: "Premium",
    licenseExpiry: "2025-03-31",
    primaryContact: "Meera Rao",
    primaryEmail: "meera.rao@stanzaliving.com",
    primaryPhone: "+91 98765 43241",
    guestAccessEnabled: true,
    authenticationConfig: {
      residents: ['username_password', 'otp_rmn', 'otp_mn', 'wpa2_psk'],
      guests: ['otp_mn', 'sponsored_employee', 'voucher_auto_account'],
      devices: ['mac_auth', 'wpa2_psk']
    },
    infrastructure: {
      apVendor: "ruckus",
      apModel: "R550",
      deployedApCount: 35,
      liveApCount: 34,
      indoorApCount: 32,
      outdoorApCount: 3,
      poeSwitchVendor: "tp_link",
      poeSwitchCount: 5,
      livePoeSwitchCount: 5,
      totalPoePorts: 120,
      usedPoePorts: 82,
      nasCount: 1,
      firewallCount: 1,
      upsCount: 2,
    },
  },
  {
    id: "site_010",
    customerId: "cust_007",
    customerName: "Stanza Living",
    name: "Stanza Living Berlin",
    city: "Chennai",
    state: "Tamil Nadu",
    region: "South",
    type: "Co-Living",
    status: "maintenance",
    deploymentDate: "2023-06-01",
    lastSeen: "2024-01-15T08:00:00",
    totalUsers: 220,
    activeUsers: 0,
    totalDevices: 115,
    onlineDevices: 20,
    bandwidthUsage: 50,
    bandwidthLimit: 500,
    storageUsed: 18,
    storageLimit: 50,
    activeConnections: 0,
    dailyDataTransfer: 0.1,
    uptime: 92.50,
    alerts: 3,
    criticalAlerts: 1,
    licenseTier: "Premium",
    licenseExpiry: "2025-03-31",
    primaryContact: "Karthik Subramanian",
    primaryEmail: "karthik.s@stanzaliving.com",
    primaryPhone: "+91 98765 43242",
    guestAccessEnabled: false,
    authenticationConfig: {
      residents: ['username_password', 'otp_rmn', 'wpa2_psk'],
      guests: ['otp_mn'],
      devices: ['mac_auth', 'wpa2_psk']
    },
    infrastructure: {
      apVendor: "edgecore",
      apModel: "EAP101",
      deployedApCount: 28,
      liveApCount: 5,
      indoorApCount: 25,
      outdoorApCount: 3,
      poeSwitchVendor: "edgecore",
      poeSwitchCount: 4,
      livePoeSwitchCount: 1,
      totalPoePorts: 96,
      usedPoePorts: 65,
      nasCount: 1,
      firewallCount: 1,
      upsCount: 2,
    },
  },
  // TCS Enterprise Site
  {
    id: "site_011",
    customerId: "cust_010",
    customerName: "Tata Consultancy Services",
    name: "TCS Olympus, Hyderabad",
    city: "Hyderabad",
    state: "Telangana",
    region: "South",
    type: "Enterprise",
    status: "online",
    deploymentDate: "2023-01-15",
    lastSeen: "2024-01-15T10:30:00",
    totalUsers: 2500,
    activeUsers: 2150,
    totalDevices: 1800,
    onlineDevices: 1750,
    bandwidthUsage: 4500,
    bandwidthLimit: 5000,
    storageUsed: 280,
    storageLimit: 500,
    activeConnections: 4200,
    dailyDataTransfer: 15.6,
    uptime: 99.99,
    alerts: 1,
    criticalAlerts: 0,
    licenseTier: "Enterprise",
    licenseExpiry: "2025-12-31",
    primaryContact: "Venkat Raghavan",
    primaryEmail: "venkat.raghavan@tcs.com",
    primaryPhone: "+91 98765 43300",
    guestAccessEnabled: true,
    authenticationConfig: {
      users: ['username_password', 'employee_id_password', 'adfs_sso', 'digital_certificate', 'wpa2_psk'],
      guests: ['otp_mn', 'sponsored_employee', 'coupon_voucher'],
      conferenceRooms: ['event_code', 'sponsored_authority'],
      devices: ['mac_auth', 'wpa2_psk']
    },
    infrastructure: {
      apVendor: "cisco",
      apModel: "Catalyst 9120AXI",
      deployedApCount: 320,
      liveApCount: 318,
      indoorApCount: 300,
      outdoorApCount: 20,
      poeSwitchVendor: "cisco",
      poeSwitchCount: 45,
      livePoeSwitchCount: 45,
      totalPoePorts: 1080,
      usedPoePorts: 820,
      nasCount: 6,
      firewallCount: 4,
      upsCount: 12,
    },
  },
  // Infosys Office Site
  {
    id: "site_012",
    customerId: "cust_011",
    customerName: "Infosys Limited",
    name: "Infosys SEZ, Pune",
    city: "Pune",
    state: "Maharashtra",
    region: "West",
    type: "Office",
    status: "online",
    deploymentDate: "2023-03-01",
    lastSeen: "2024-01-15T10:28:00",
    totalUsers: 1200,
    activeUsers: 980,
    totalDevices: 850,
    onlineDevices: 830,
    bandwidthUsage: 1800,
    bandwidthLimit: 2000,
    storageUsed: 120,
    storageLimit: 200,
    activeConnections: 1950,
    dailyDataTransfer: 6.8,
    uptime: 99.95,
    alerts: 0,
    criticalAlerts: 0,
    licenseTier: "Enterprise",
    licenseExpiry: "2025-06-30",
    primaryContact: "Priya Menon",
    primaryEmail: "priya.menon@infosys.com",
    primaryPhone: "+91 98765 43310",
    guestAccessEnabled: true,
    authenticationConfig: {
      users: ['username_password', 'employee_id_password', 'otp_rmn', 'wpa2_psk'],
      guests: ['otp_mn', 'sponsored_employee'],
      devices: ['mac_auth', 'wpa2_psk']
    },
    infrastructure: {
      apVendor: "aruba",
      apModel: "AP-535",
      deployedApCount: 180,
      liveApCount: 178,
      indoorApCount: 165,
      outdoorApCount: 15,
      poeSwitchVendor: "aruba",
      poeSwitchCount: 24,
      livePoeSwitchCount: 24,
      totalPoePorts: 576,
      usedPoePorts: 425,
      nasCount: 3,
      firewallCount: 2,
      upsCount: 6,
    },
  },
  // Community Center Miscellaneous Site
  {
    id: "site_013",
    customerId: "cust_012",
    customerName: "Delhi Municipal Corporation",
    name: "Connaught Place Community Hub",
    city: "New Delhi",
    state: "Delhi",
    region: "North",
    type: "Miscellaneous",
    status: "online",
    deploymentDate: "2023-09-01",
    lastSeen: "2024-01-15T10:25:00",
    totalUsers: 450,
    activeUsers: 320,
    totalDevices: 280,
    onlineDevices: 265,
    bandwidthUsage: 380,
    bandwidthLimit: 500,
    storageUsed: 35,
    storageLimit: 80,
    activeConnections: 580,
    dailyDataTransfer: 1.2,
    uptime: 99.80,
    alerts: 2,
    criticalAlerts: 0,
    licenseTier: "Standard",
    licenseExpiry: "2024-09-30",
    primaryContact: "Rakesh Sharma",
    primaryEmail: "rakesh.sharma@dmc.gov.in",
    primaryPhone: "+91 98765 43320",
    guestAccessEnabled: true,
    authenticationConfig: {
      users: ['username_password', 'otp_rmn', 'otp_mn', 'wpa2_psk'],
      guests: ['otp_mn', 'coupon_voucher', 'event_code'],
      devices: ['mac_auth', 'wpa2_psk']
    },
    infrastructure: {
      apVendor: "tp_link",
      apModel: "EAP670",
      deployedApCount: 45,
      liveApCount: 43,
      indoorApCount: 35,
      outdoorApCount: 10,
      poeSwitchVendor: "tp_link",
      poeSwitchCount: 6,
      livePoeSwitchCount: 6,
      totalPoePorts: 144,
      usedPoePorts: 98,
      nasCount: 1,
      firewallCount: 1,
      upsCount: 3,
    },
  },
];

/**
 * System Alerts & Notifications
 */
export const systemAlerts = [
  {
    id: "alert_001",
    type: "critical",
    category: "connectivity",
    title: "Site Offline",
    message: "Zolo Starter, HSR Layout has been offline for 12 hours",
    siteId: "site_007",
    siteName: "Zolo Starter, HSR Layout",
    customerId: "cust_004",
    customerName: "Zolo Stays",
    timestamp: "2024-01-15T10:15:00",
    acknowledged: false,
    assignedTo: null,
  },
  {
    id: "alert_002",
    type: "critical",
    category: "performance",
    title: "High Packet Loss",
    message: "The Oberoi, Bangalore experiencing 15% packet loss on primary link",
    siteId: "site_003",
    siteName: "The Oberoi, Bangalore",
    customerId: "cust_001",
    customerName: "Oberoi Hotels & Resorts",
    timestamp: "2024-01-15T09:45:00",
    acknowledged: true,
    assignedTo: "Deployment Team",
  },
  {
    id: "alert_003",
    type: "critical",
    category: "maintenance",
    title: "Scheduled Maintenance Active",
    message: "Stanza Living Berlin undergoing planned network upgrade",
    siteId: "site_010",
    siteName: "Stanza Living Berlin",
    customerId: "cust_007",
    customerName: "Stanza Living",
    timestamp: "2024-01-15T08:00:00",
    acknowledged: true,
    assignedTo: "Network Operations",
  },
  {
    id: "alert_004",
    type: "warning",
    category: "capacity",
    title: "Bandwidth Threshold Exceeded",
    message: "WeWork BKC, Mumbai at 88% bandwidth capacity",
    siteId: "site_005",
    siteName: "WeWork BKC, Mumbai",
    customerId: "cust_002",
    customerName: "WeWork India",
    timestamp: "2024-01-15T10:00:00",
    acknowledged: false,
    assignedTo: null,
  },
  {
    id: "alert_005",
    type: "warning",
    category: "license",
    title: "License Expiring Soon",
    message: "WeWork India license expires in 45 days",
    siteId: null,
    siteName: null,
    customerId: "cust_002",
    customerName: "WeWork India",
    timestamp: "2024-01-15T00:00:00",
    acknowledged: false,
    assignedTo: "Account Management",
  },
  {
    id: "alert_006",
    type: "warning",
    category: "security",
    title: "Multiple Failed Login Attempts",
    message: "25 failed login attempts detected at The Oberoi, Delhi",
    siteId: "site_002",
    siteName: "The Oberoi, Delhi",
    customerId: "cust_001",
    customerName: "Oberoi Hotels & Resorts",
    timestamp: "2024-01-15T07:30:00",
    acknowledged: true,
    assignedTo: "Security Team",
  },
  {
    id: "alert_007",
    type: "info",
    category: "deployment",
    title: "New Site Provisioned",
    message: "OYO Residency, Gurgaon successfully provisioned",
    siteId: "site_new_001",
    siteName: "OYO Residency, Gurgaon",
    customerId: "cust_008",
    customerName: "OYO Rooms",
    timestamp: "2024-01-14T16:00:00",
    acknowledged: true,
    assignedTo: null,
  },
  {
    id: "alert_008",
    type: "info",
    category: "system",
    title: "Firmware Update Available",
    message: "New firmware v2.5.1 available for AP devices",
    siteId: null,
    siteName: null,
    customerId: null,
    customerName: null,
    timestamp: "2024-01-14T12:00:00",
    acknowledged: false,
    assignedTo: null,
  },
];

/**
 * Support Tickets
 */
export const supportTickets = [
  {
    id: "ticket_001",
    customerId: "cust_001",
    customerName: "Oberoi Hotels & Resorts",
    siteId: "site_003",
    siteName: "The Oberoi, Bangalore",
    subject: "Intermittent connectivity issues in conference rooms",
    description: "Guests reporting WiFi drops during video calls in conference area",
    priority: "high",
    status: "in_progress",
    category: "connectivity",
    createdAt: "2024-01-14T14:30:00",
    updatedAt: "2024-01-15T09:00:00",
    assignedTo: "Ravi Kumar",
    slaDeadline: "2024-01-15T14:30:00",
    responses: 3,
  },
  {
    id: "ticket_002",
    customerId: "cust_004",
    customerName: "Zolo Stays",
    siteId: "site_007",
    siteName: "Zolo Starter, HSR Layout",
    subject: "Complete network outage",
    description: "No internet connectivity since last night. All residents affected.",
    priority: "critical",
    status: "open",
    category: "outage",
    createdAt: "2024-01-15T08:00:00",
    updatedAt: "2024-01-15T10:15:00",
    assignedTo: "Emergency Response Team",
    slaDeadline: "2024-01-15T12:00:00",
    responses: 5,
  },
  {
    id: "ticket_003",
    customerId: "cust_002",
    customerName: "WeWork India",
    siteId: "site_005",
    siteName: "WeWork BKC, Mumbai",
    subject: "Request for bandwidth upgrade",
    description: "Current bandwidth insufficient for growing member base. Need upgrade to 5Gbps.",
    priority: "medium",
    status: "pending_approval",
    category: "upgrade",
    createdAt: "2024-01-13T11:00:00",
    updatedAt: "2024-01-14T16:00:00",
    assignedTo: "Account Management",
    slaDeadline: "2024-01-16T11:00:00",
    responses: 2,
  },
  {
    id: "ticket_004",
    customerId: "cust_007",
    customerName: "Stanza Living",
    siteId: "site_010",
    siteName: "Stanza Living Berlin",
    subject: "Scheduled maintenance notification",
    description: "Network upgrade scheduled for infrastructure improvements",
    priority: "low",
    status: "scheduled",
    category: "maintenance",
    createdAt: "2024-01-10T10:00:00",
    updatedAt: "2024-01-15T08:00:00",
    assignedTo: "Network Operations",
    slaDeadline: "2024-01-16T20:00:00",
    responses: 4,
  },
  {
    id: "ticket_005",
    customerId: "cust_005",
    customerName: "ITC Hotels",
    siteId: null,
    siteName: "All Sites",
    subject: "Security audit report request",
    description: "Requesting comprehensive security audit report for compliance",
    priority: "medium",
    status: "completed",
    category: "compliance",
    createdAt: "2024-01-08T09:00:00",
    updatedAt: "2024-01-12T17:00:00",
    assignedTo: "Security Team",
    slaDeadline: "2024-01-15T09:00:00",
    responses: 6,
  },
];

/**
 * License Information
 */
export const licenses = [
  {
    id: "lic_001",
    customerId: "cust_001",
    customerName: "Oberoi Hotels & Resorts",
    tier: "Premium",
    type: "Enterprise",
    maxSites: 15,
    usedSites: 12,
    maxUsers: 5000,
    usedUsers: 2450,
    maxDevices: 5000,
    usedDevices: 3200,
    startDate: "2023-01-15",
    expiryDate: "2025-01-14",
    autoRenew: true,
    monthlyFee: 485000,
    status: "active",
  },
  {
    id: "lic_002",
    customerId: "cust_002",
    customerName: "WeWork India",
    tier: "Enterprise",
    type: "Enterprise",
    maxSites: 50,
    usedSites: 28,
    maxUsers: 20000,
    usedUsers: 15200,
    maxDevices: 15000,
    usedDevices: 8500,
    startDate: "2022-06-01",
    expiryDate: "2024-05-31",
    autoRenew: false,
    monthlyFee: 1250000,
    status: "expiring_soon",
  },
  {
    id: "lic_003",
    customerId: "cust_004",
    customerName: "Zolo Stays",
    tier: "Standard",
    type: "SMB",
    maxSites: 150,
    usedSites: 120,
    maxUsers: 30000,
    usedUsers: 24000,
    maxDevices: 15000,
    usedDevices: 12000,
    startDate: "2023-07-20",
    expiryDate: "2024-07-19",
    autoRenew: true,
    monthlyFee: 890000,
    status: "active",
  },
  {
    id: "lic_004",
    customerId: "cust_007",
    customerName: "Stanza Living",
    tier: "Premium",
    type: "Enterprise",
    maxSites: 100,
    usedSites: 85,
    maxUsers: 25000,
    usedUsers: 18500,
    maxDevices: 12000,
    usedDevices: 9200,
    startDate: "2023-04-01",
    expiryDate: "2025-03-31",
    autoRenew: true,
    monthlyFee: 1150000,
    status: "active",
  },
  {
    id: "lic_005",
    customerId: "cust_010",
    customerName: "Innov8 Coworking",
    tier: "Standard",
    type: "SMB",
    maxSites: 20,
    usedSites: 15,
    maxUsers: 5000,
    usedUsers: 2800,
    maxDevices: 3000,
    usedDevices: 1500,
    startDate: "2023-01-01",
    expiryDate: "2023-12-31",
    autoRenew: false,
    monthlyFee: 0,
    status: "expired",
  },
];

/**
 * Platform Analytics Summary
 */
export const platformMetrics = {
  overview: {
    totalCustomers: 10,
    activeCustomers: 9,
    totalSites: 663,
    activeSites: 547,
    totalUsers: 132350,
    activeUsers: 98500,
    totalDevices: 81300,
    onlineDevices: 72800,
    totalBandwidth: 125000, // Mbps provisioned
    usedBandwidth: 89500, // Mbps in use
    totalLicenses: 150000, // Total licenses across all customers
  },
  trends: {
    userGrowth: 12.5, // % month over month
    siteGrowth: 8.2,
    deviceGrowth: 10.4,
    churnRate: 2.1,
  },
  health: {
    sitesOnline: 534,
    sitesDegraded: 8,
    sitesOffline: 3,
    sitesMaintenance: 2,
    averageUptime: 99.2,
    criticalAlerts: 3,
    warningAlerts: 12,
    infoAlerts: 8,
    licenseUtilization: 88, // percentage of licenses in use
  },
  regional: [
    { region: "North", sites: 85, users: 18500, devices: 12500 },
    { region: "South", sites: 245, users: 52000, devices: 35200 },
    { region: "East", sites: 78, users: 14200, devices: 9800 },
    { region: "West", sites: 255, users: 47650, devices: 23800 },
  ],
  bySegment: [
    { segment: "Hotel", customers: 4, sites: 335, users: 52200, devices: 36100 },
    { segment: "Co-Working", customers: 3, sites: 78, users: 30500, devices: 21500 },
    { segment: "Co-Living", customers: 2, sites: 130, users: 27400, devices: 13400 },
    { segment: "PG", customers: 1, sites: 120, users: 24000, devices: 12000 },
    { segment: "Enterprise", customers: 5, sites: 425, users: 45800, devices: 32500 },
    { segment: "Misc", customers: 2, sites: 35, users: 8200, devices: 4800 },
  ],
};

/**
 * Activity Logs for Internal Portal
 */
export const activityLogs = [
  {
    id: "log_001",
    timestamp: "2025-12-19T10:30:00",
    user: "Priya Sharma",
    userRole: "Super Admin",
    action: "site_provisioned",
    description: "Provisioned new site: OYO Residency, Gurgaon",
    customerId: "cust_008",
    customerName: "OYO Rooms",
    siteId: "site_new_001",
    siteName: "OYO Residency Gurgaon",
    ipAddress: "192.168.1.100",
    userType: "internal",
    category: "Site Management",
    severity: "info",
    status: "success",
  },
  {
    id: "log_002",
    timestamp: "2025-12-19T10:15:00",
    user: "System",
    userRole: "Automated",
    action: "alert_generated",
    description: "Critical alert: Site offline - Zolo Starter, HSR Layout",
    customerId: "cust_004",
    customerName: "Zolo Stays",
    siteId: "site_007",
    siteName: "Zolo House HSR",
    ipAddress: null,
    userType: "internal",
    category: "Monitoring",
    severity: "critical",
    status: "triggered",
  },
  {
    id: "log_003",
    timestamp: "2025-12-19T09:45:00",
    user: "Ravi Kumar",
    userRole: "Support Engineer",
    action: "ticket_updated",
    description: "Updated ticket #001: Added diagnostic report",
    customerId: "cust_001",
    customerName: "Oberoi Hotels & Resorts",
    siteId: "site_003",
    siteName: "The Oberoi Udaivilas",
    ipAddress: "192.168.1.105",
    userType: "internal",
    category: "Support",
    severity: "info",
    status: "success",
  },
  {
    id: "log_004",
    timestamp: "2025-12-19T09:00:00",
    user: "Rahul Mehta",
    userRole: "Deployment Engineer",
    action: "config_changed",
    description: "Updated bandwidth limits for WeWork BKC, Mumbai",
    customerId: "cust_002",
    customerName: "WeWork India",
    siteId: "site_005",
    siteName: "WeWork BKC Mumbai",
    ipAddress: "192.168.1.102",
    userType: "internal",
    category: "Configuration",
    severity: "info",
    status: "success",
  },
  {
    id: "log_005",
    timestamp: "2025-12-19T08:00:00",
    user: "System",
    userRole: "Automated",
    action: "maintenance_started",
    description: "Scheduled maintenance started: Stanza Living Berlin",
    customerId: "cust_007",
    customerName: "Stanza Living",
    siteId: "site_010",
    siteName: "Stanza Living Bangalore",
    ipAddress: null,
    userType: "internal",
    category: "Maintenance",
    severity: "info",
    status: "success",
  },
  {
    id: "log_006",
    timestamp: "2025-12-18T16:00:00",
    user: "Anita Desai",
    userRole: "Super Admin",
    action: "user_created",
    description: "Created new admin user for Stanza Living",
    customerId: "cust_007",
    customerName: "Stanza Living",
    siteId: null,
    siteName: null,
    ipAddress: "192.168.1.101",
    userType: "internal",
    category: "User Management",
    severity: "info",
    status: "success",
  },
  {
    id: "log_007",
    timestamp: "2025-12-18T14:30:00",
    user: "Customer Portal",
    userRole: "Customer",
    action: "ticket_created",
    description: "New support ticket: Intermittent connectivity issues",
    customerId: "cust_001",
    customerName: "Oberoi Hotels & Resorts",
    siteId: "site_003",
    siteName: "The Oberoi Udaivilas",
    ipAddress: "203.45.67.89",
    userType: "customer",
    category: "Support",
    severity: "info",
    status: "success",
  },
  {
    id: "log_008",
    timestamp: "2025-12-18T12:00:00",
    user: "System",
    userRole: "Automated",
    action: "firmware_available",
    description: "New firmware v2.5.1 available for distribution",
    customerId: null,
    customerName: null,
    siteId: null,
    siteName: null,
    ipAddress: null,
    userType: "internal",
    category: "System",
    severity: "info",
    status: "success",
  },
  // Additional comprehensive audit logs
  {
    id: "log_009",
    timestamp: "2025-12-19T11:30:00",
    user: "Vikram Singh",
    userRole: "Deployment Engineer",
    action: "site_config_updated",
    description: "Updated NAS IP configuration for WeWork Galaxy, Bangalore",
    customerId: "cust_002",
    customerName: "WeWork India",
    siteId: "site_004",
    siteName: "WeWork Galaxy Bangalore",
    ipAddress: "192.168.1.108",
    userType: "internal",
    category: "Configuration",
    severity: "info",
    status: "success",
  },
  {
    id: "log_010",
    timestamp: "2025-12-19T11:00:00",
    user: "Sneha Reddy",
    userRole: "Account Manager",
    action: "contract_renewed",
    description: "Renewed contract for Oberoi Hotels - 2 year extension",
    customerId: "cust_001",
    customerName: "Oberoi Hotels & Resorts",
    siteId: null,
    siteName: null,
    ipAddress: "192.168.1.115",
    userType: "internal",
    category: "License Management",
    severity: "info",
    status: "success",
  },
  {
    id: "log_011",
    timestamp: "2025-12-19T10:45:00",
    user: "Amit Verma",
    userRole: "Network Admin",
    action: "ap_registered",
    description: "Registered 5 new access points at WeWork BKC",
    customerId: "cust_002",
    customerName: "WeWork India",
    siteId: "site_005",
    siteName: "WeWork BKC Mumbai",
    ipAddress: "10.0.20.15",
    userType: "customer",
    category: "Device Management",
    severity: "info",
    status: "success",
  },
  {
    id: "log_012",
    timestamp: "2025-12-19T07:30:00",
    user: "System",
    userRole: "Automated",
    action: "backup_completed",
    description: "Daily database backup completed successfully (312 GB)",
    customerId: null,
    customerName: null,
    siteId: null,
    siteName: null,
    ipAddress: null,
    userType: "internal",
    category: "System",
    severity: "info",
    status: "success",
  },
  {
    id: "log_013",
    timestamp: "2025-12-19T07:15:00",
    user: "Unknown",
    userRole: "N/A",
    action: "login_failed",
    description: "Failed login attempt - invalid credentials (5 attempts)",
    customerId: "cust_001",
    customerName: "Oberoi Hotels & Resorts",
    siteId: "site_002",
    siteName: "The Oberoi New Delhi",
    ipAddress: "103.25.40.112",
    userType: "customer",
    category: "Authentication",
    severity: "warning",
    status: "failed",
  },
  {
    id: "log_014",
    timestamp: "2025-12-18T17:45:00",
    user: "Priya Sharma",
    userRole: "Support Engineer",
    action: "ticket_resolved",
    description: "Resolved ticket #TKT-2024-0891 - Network connectivity issue fixed",
    customerId: "cust_004",
    customerName: "Zolo Stays",
    siteId: "site_006",
    siteName: "Zolo Starter HSR",
    ipAddress: "192.168.1.105",
    userType: "internal",
    category: "Support",
    severity: "info",
    status: "success",
  },
  {
    id: "log_015",
    timestamp: "2025-12-18T15:30:00",
    user: "Kavitha Nair",
    userRole: "Site Admin",
    action: "user_password_reset",
    description: "Reset password for 3 user accounts",
    customerId: "cust_004",
    customerName: "Zolo Stays",
    siteId: "site_006",
    siteName: "Zolo Starter HSR",
    ipAddress: "10.0.25.42",
    userType: "customer",
    category: "User Management",
    severity: "info",
    status: "success",
  },
  {
    id: "log_016",
    timestamp: "2024-01-14T09:00:00",
    user: "System",
    userRole: "Automated",
    action: "ssl_expiry_warning",
    description: "SSL certificate for site_008 expires in 30 days",
    customerId: "cust_007",
    siteId: "site_008",
    ipAddress: null,
    userType: "internal",
    category: "Security",
    severity: "warning",
    status: "pending",
  },
  {
    id: "log_017",
    timestamp: "2024-01-14T08:30:00",
    user: "Rahul Mehta",
    userRole: "Deployment Engineer",
    action: "firmware_deployed",
    description: "Deployed firmware v2.5.0 to 15 access points at Oberoi Mumbai",
    customerId: "cust_001",
    siteId: "site_001",
    ipAddress: "192.168.1.102",
    userType: "internal",
    category: "Maintenance",
    severity: "info",
    status: "success",
  },
  {
    id: "log_018",
    timestamp: "2024-01-14T08:00:00",
    user: "Deepak Joshi",
    userRole: "Manager",
    action: "report_exported",
    description: "Exported monthly usage report for Stanza Living Madrid",
    customerId: "cust_007",
    siteId: "site_008",
    ipAddress: "10.0.35.18",
    userType: "customer",
    category: "Reports",
    severity: "info",
    status: "success",
  },
  {
    id: "log_019",
    timestamp: "2024-01-13T18:30:00",
    user: "System",
    userRole: "Automated",
    action: "threshold_exceeded",
    description: "Bandwidth threshold exceeded at WeWork BKC (95% utilization)",
    customerId: "cust_002",
    siteId: "site_005",
    ipAddress: null,
    userType: "internal",
    category: "Monitoring",
    severity: "warning",
    status: "triggered",
  },
  {
    id: "log_020",
    timestamp: "2024-01-13T17:45:00",
    user: "Anita Desai",
    userRole: "Super Admin",
    action: "permission_updated",
    description: "Updated role permissions for Zolo Stays admin team",
    customerId: "cust_004",
    siteId: null,
    ipAddress: "192.168.1.101",
    userType: "internal",
    category: "User Management",
    severity: "info",
    status: "success",
  },
  {
    id: "log_021",
    timestamp: "2024-01-13T16:00:00",
    user: "Rajesh Kumar",
    userRole: "Site Admin",
    action: "policy_created",
    description: "Created new bandwidth policy for premium guests",
    customerId: "cust_001",
    siteId: "site_001",
    ipAddress: "10.0.15.42",
    userType: "customer",
    category: "Policy Management",
    severity: "info",
    status: "success",
  },
  {
    id: "log_022",
    timestamp: "2024-01-13T15:30:00",
    user: "Vikram Singh",
    userRole: "Deployment Engineer",
    action: "site_activated",
    description: "Activated new site: Zolo Sunrise, Pune - 45 user licenses",
    customerId: "cust_004",
    siteId: "site_new_002",
    ipAddress: "192.168.1.108",
    userType: "internal",
    category: "Site Management",
    severity: "info",
    status: "success",
  },
  {
    id: "log_023",
    timestamp: "2024-01-13T14:15:00",
    user: "System",
    userRole: "Automated",
    action: "auto_recovery",
    description: "Auto-recovered AP-OB-MUM-023 after brief disconnection",
    customerId: "cust_001",
    siteId: "site_001",
    ipAddress: null,
    userType: "internal",
    category: "System",
    severity: "info",
    status: "success",
  },
  {
    id: "log_024",
    timestamp: "2024-01-13T13:00:00",
    user: "Sneha Patel",
    userRole: "Admin",
    action: "bulk_user_import",
    description: "Imported 25 new user accounts via CSV upload",
    customerId: "cust_003",
    siteId: "site_new_003",
    ipAddress: "10.0.25.30",
    userType: "customer",
    category: "User Management",
    severity: "info",
    status: "success",
  },
  {
    id: "log_025",
    timestamp: "2024-01-13T12:30:00",
    user: "Ravi Kumar",
    userRole: "Support Engineer",
    action: "remote_diagnostic",
    description: "Performed remote diagnostic on degraded site Oberoi Bangalore",
    customerId: "cust_001",
    siteId: "site_003",
    ipAddress: "192.168.1.105",
    userType: "internal",
    category: "Support",
    severity: "info",
    status: "success",
  },
  {
    id: "log_026",
    timestamp: "2024-01-13T11:45:00",
    user: "System",
    userRole: "Automated",
    action: "license_sync",
    description: "License synchronization completed for all customers",
    customerId: null,
    siteId: null,
    ipAddress: null,
    userType: "internal",
    category: "License Management",
    severity: "info",
    status: "success",
  },
  {
    id: "log_027",
    timestamp: "2024-01-13T10:30:00",
    user: "Arjun Patel",
    userRole: "Network Admin",
    action: "vlan_configured",
    description: "Configured new VLAN for guest network segregation",
    customerId: "cust_002",
    siteId: "site_005",
    ipAddress: "10.0.20.20",
    userType: "customer",
    category: "Configuration",
    severity: "info",
    status: "success",
  },
  {
    id: "log_028",
    timestamp: "2024-01-13T09:15:00",
    user: "Priya Sharma",
    userRole: "Support Engineer",
    action: "escalation_created",
    description: "Escalated ticket #TKT-2024-0885 to Level 3 support",
    customerId: "cust_007",
    siteId: "site_010",
    ipAddress: "192.168.1.105",
    userType: "internal",
    category: "Support",
    severity: "warning",
    status: "success",
  },
  {
    id: "log_029",
    timestamp: "2024-01-13T08:00:00",
    user: "System",
    userRole: "Automated",
    action: "daily_report_generated",
    description: "Generated daily platform health report",
    customerId: null,
    siteId: null,
    ipAddress: null,
    userType: "internal",
    category: "Reports",
    severity: "info",
    status: "success",
  },
  {
    id: "log_030",
    timestamp: "2024-01-12T19:00:00",
    user: "Meera Rao",
    userRole: "Manager",
    action: "bulk_device_register",
    description: "Registered 8 new PoE switches at Stanza Florence",
    customerId: "cust_007",
    siteId: "site_009",
    ipAddress: "10.0.35.25",
    userType: "customer",
    category: "Device Management",
    severity: "info",
    status: "success",
  },
  // ==========================================
  // Extended Audit Logs - Comprehensive Data
  // Across all customers, segments, and actions
  // ==========================================

  // --- Enterprise Segment: TCS ---
  {
    id: "log_031",
    timestamp: "2024-01-15T14:30:00",
    user: "Venkat Raghavan",
    userRole: "IT Admin",
    action: "user_bulk_import",
    description: "Imported 250 employee accounts from HR system",
    customerId: "cust_010",
    customerName: "Tata Consultancy Services",
    siteId: "site_tcs_001",
    siteName: "TCS Siruseri, Chennai",
    ipAddress: "10.45.20.15",
    userType: "customer",
    category: "User Management",
    severity: "info",
    status: "success",
  },
  {
    id: "log_032",
    timestamp: "2024-01-15T14:15:00",
    user: "Priya Sharma",
    userRole: "Account Manager",
    action: "license_upgraded",
    description: "Upgraded TCS license from 80,000 to 100,000 users",
    customerId: "cust_010",
    customerName: "Tata Consultancy Services",
    siteId: null,
    siteName: null,
    ipAddress: "192.168.1.105",
    userType: "internal",
    category: "License Management",
    severity: "info",
    status: "success",
  },
  {
    id: "log_033",
    timestamp: "2024-01-15T13:45:00",
    user: "System",
    userRole: "Automated",
    action: "security_scan_completed",
    description: "Quarterly security scan completed - 2 vulnerabilities found",
    customerId: "cust_010",
    customerName: "Tata Consultancy Services",
    siteId: "site_tcs_002",
    siteName: "TCS Manyata, Bangalore",
    ipAddress: null,
    userType: "internal",
    category: "Security",
    severity: "warning",
    status: "success",
  },
  {
    id: "log_034",
    timestamp: "2024-01-15T13:30:00",
    user: "Anand Kumar",
    userRole: "Network Engineer",
    action: "firewall_rule_updated",
    description: "Updated firewall rules for guest WiFi isolation",
    customerId: "cust_010",
    customerName: "Tata Consultancy Services",
    siteId: "site_tcs_003",
    siteName: "TCS Whitefield, Bangalore",
    ipAddress: "10.45.30.22",
    userType: "customer",
    category: "Security",
    severity: "info",
    status: "success",
  },

  // --- Enterprise Segment: Infosys ---
  {
    id: "log_035",
    timestamp: "2024-01-15T13:00:00",
    user: "Priya Menon",
    userRole: "IT Director",
    action: "policy_created",
    description: "Created new bandwidth policy for Video Conferencing priority",
    customerId: "cust_011",
    customerName: "Infosys Limited",
    siteId: null,
    siteName: null,
    ipAddress: "10.50.10.5",
    userType: "customer",
    category: "Policy Management",
    severity: "info",
    status: "success",
  },
  {
    id: "log_036",
    timestamp: "2024-01-15T12:45:00",
    user: "Rahul Mehta",
    userRole: "Support Engineer",
    action: "ap_firmware_scheduled",
    description: "Scheduled firmware update for 450 APs at Infosys Mysore DC",
    customerId: "cust_011",
    customerName: "Infosys Limited",
    siteId: "site_infy_001",
    siteName: "Infosys Mysore Development Center",
    ipAddress: "192.168.1.110",
    userType: "internal",
    category: "Maintenance",
    severity: "info",
    status: "scheduled",
  },
  {
    id: "log_037",
    timestamp: "2024-01-15T12:30:00",
    user: "Karthik Subramanian",
    userRole: "Site Admin",
    action: "guest_network_enabled",
    description: "Enabled guest network for Infosys client visit area",
    customerId: "cust_011",
    customerName: "Infosys Limited",
    siteId: "site_infy_002",
    siteName: "Infosys Electronic City, Bangalore",
    ipAddress: "10.50.20.30",
    userType: "customer",
    category: "Configuration",
    severity: "info",
    status: "success",
  },

  // --- Government Segment: Delhi Municipal ---
  {
    id: "log_038",
    timestamp: "2024-01-15T12:00:00",
    user: "Rakesh Sharma",
    userRole: "IT Head",
    action: "compliance_report_generated",
    description: "Generated quarterly compliance report for government audit",
    customerId: "cust_012",
    customerName: "Delhi Municipal Corporation",
    siteId: null,
    siteName: null,
    ipAddress: "10.60.10.5",
    userType: "customer",
    category: "Reports",
    severity: "info",
    status: "success",
  },
  {
    id: "log_039",
    timestamp: "2024-01-15T11:45:00",
    user: "Vikram Singh",
    userRole: "Deployment Engineer",
    action: "site_provisioned",
    description: "Provisioned new site: DMC Civic Center, South Delhi",
    customerId: "cust_012",
    customerName: "Delhi Municipal Corporation",
    siteId: "site_dmc_new",
    siteName: "DMC Civic Center South Delhi",
    ipAddress: "192.168.1.108",
    userType: "internal",
    category: "Site Management",
    severity: "info",
    status: "success",
  },
  {
    id: "log_040",
    timestamp: "2024-01-15T11:30:00",
    user: "System",
    userRole: "Automated",
    action: "certificate_expiry_alert",
    description: "SSL certificate expiring in 30 days for public WiFi portal",
    customerId: "cust_012",
    customerName: "Delhi Municipal Corporation",
    siteId: "site_dmc_001",
    siteName: "DMC Headquarters, Connaught Place",
    ipAddress: null,
    userType: "internal",
    category: "Security",
    severity: "warning",
    status: "pending",
  },

  // --- Hotel Segment: Oberoi Hotels ---
  {
    id: "log_041",
    timestamp: "2024-01-15T11:00:00",
    user: "Rajesh Kumar",
    userRole: "IT Manager",
    action: "pms_integration_updated",
    description: "Updated Opera PMS integration for room-based authentication",
    customerId: "cust_001",
    customerName: "Oberoi Hotels & Resorts",
    siteId: "site_001",
    siteName: "The Oberoi, Mumbai",
    ipAddress: "10.10.10.15",
    userType: "customer",
    category: "Auth Configuration",
    severity: "info",
    status: "success",
  },
  {
    id: "log_042",
    timestamp: "2024-01-15T10:45:00",
    user: "Amit Khanna",
    userRole: "Guest Services Manager",
    action: "voucher_batch_created",
    description: "Created batch of 500 guest WiFi vouchers for conference",
    customerId: "cust_001",
    customerName: "Oberoi Hotels & Resorts",
    siteId: "site_001",
    siteName: "The Oberoi, Mumbai",
    ipAddress: "10.10.10.45",
    userType: "customer",
    category: "User Management",
    severity: "info",
    status: "success",
  },
  {
    id: "log_043",
    timestamp: "2024-01-15T10:30:00",
    user: "System",
    userRole: "Automated",
    action: "bandwidth_threshold_alert",
    description: "Bandwidth usage exceeded 85% threshold during peak hours",
    customerId: "cust_001",
    customerName: "Oberoi Hotels & Resorts",
    siteId: "site_002",
    siteName: "The Oberoi, Delhi",
    ipAddress: null,
    userType: "internal",
    category: "Monitoring",
    severity: "warning",
    status: "triggered",
  },

  // --- Hotel Segment: ITC Hotels ---
  {
    id: "log_044",
    timestamp: "2024-01-15T10:15:00",
    user: "Suresh Menon",
    userRole: "IT Director",
    action: "sso_config_updated",
    description: "Updated SSO configuration for staff portal access",
    customerId: "cust_005",
    customerName: "ITC Hotels",
    siteId: null,
    siteName: null,
    ipAddress: "10.20.10.5",
    userType: "customer",
    category: "Auth Configuration",
    severity: "info",
    status: "success",
  },
  {
    id: "log_045",
    timestamp: "2024-01-15T10:00:00",
    user: "Priya Sharma",
    userRole: "Support Engineer",
    action: "ticket_created",
    description: "Created support ticket for AP connectivity issues",
    customerId: "cust_005",
    customerName: "ITC Hotels",
    siteId: "site_itc_001",
    siteName: "ITC Grand Chola, Chennai",
    ipAddress: "192.168.1.105",
    userType: "internal",
    category: "Support",
    severity: "warning",
    status: "success",
  },

  // --- Co-Working Segment: WeWork ---
  {
    id: "log_046",
    timestamp: "2024-01-15T09:45:00",
    user: "Amit Verma",
    userRole: "Network Admin",
    action: "member_onboarded",
    description: "Onboarded 25 new member companies with custom VLANs",
    customerId: "cust_002",
    customerName: "WeWork India",
    siteId: "site_004",
    siteName: "WeWork Galaxy, Bangalore",
    ipAddress: "10.30.10.15",
    userType: "customer",
    category: "User Management",
    severity: "info",
    status: "success",
  },
  {
    id: "log_047",
    timestamp: "2024-01-15T09:30:00",
    user: "Sneha Reddy",
    userRole: "Operations Manager",
    action: "conference_room_config",
    description: "Configured WiFi for new 50-seater conference hall",
    customerId: "cust_002",
    customerName: "WeWork India",
    siteId: "site_005",
    siteName: "WeWork BKC, Mumbai",
    ipAddress: "10.30.20.25",
    userType: "customer",
    category: "Configuration",
    severity: "info",
    status: "success",
  },
  {
    id: "log_048",
    timestamp: "2024-01-15T09:15:00",
    user: "Rahul Mehta",
    userRole: "Deployment Engineer",
    action: "site_expansion",
    description: "Added 3 new floors to WeWork Worli coverage",
    customerId: "cust_002",
    customerName: "WeWork India",
    siteId: "site_wework_006",
    siteName: "WeWork Worli, Mumbai",
    ipAddress: "192.168.1.110",
    userType: "internal",
    category: "Site Management",
    severity: "info",
    status: "success",
  },

  // --- Co-Working Segment: Awfis ---
  {
    id: "log_049",
    timestamp: "2024-01-15T09:00:00",
    user: "Kavita Sharma",
    userRole: "Admin",
    action: "access_policy_updated",
    description: "Updated day-pass access policy for meeting rooms",
    customerId: "cust_006",
    customerName: "Awfis Space Solutions",
    siteId: "site_awfis_001",
    siteName: "Awfis Connaught Place, Delhi",
    ipAddress: "10.40.10.15",
    userType: "customer",
    category: "Policy Management",
    severity: "info",
    status: "success",
  },
  {
    id: "log_050",
    timestamp: "2024-01-15T08:45:00",
    user: "System",
    userRole: "Automated",
    action: "usage_report_generated",
    description: "Generated monthly usage report for all Awfis locations",
    customerId: "cust_006",
    customerName: "Awfis Space Solutions",
    siteId: null,
    siteName: null,
    ipAddress: null,
    userType: "internal",
    category: "Reports",
    severity: "info",
    status: "success",
  },

  // --- Co-Living Segment: Nestaway ---
  {
    id: "log_051",
    timestamp: "2024-01-15T08:30:00",
    user: "Sneha Patel",
    userRole: "Admin",
    action: "resident_bulk_update",
    description: "Updated WiFi access for 150 new residents across 3 properties",
    customerId: "cust_003",
    customerName: "Nestaway Technologies",
    siteId: null,
    siteName: null,
    ipAddress: "10.25.10.20",
    userType: "customer",
    category: "User Management",
    severity: "info",
    status: "success",
  },
  {
    id: "log_052",
    timestamp: "2024-01-15T08:15:00",
    user: "Anita Desai",
    userRole: "Account Manager",
    action: "contract_amendment",
    description: "Added 10 new properties to Nestaway contract",
    customerId: "cust_003",
    customerName: "Nestaway Technologies",
    siteId: null,
    siteName: null,
    ipAddress: "192.168.1.101",
    userType: "internal",
    category: "License Management",
    severity: "info",
    status: "success",
  },
  {
    id: "log_053",
    timestamp: "2024-01-15T08:00:00",
    user: "Rohan Mehta",
    userRole: "Property Manager",
    action: "ap_reboot",
    description: "Rebooted 5 APs to resolve connectivity issues",
    customerId: "cust_003",
    customerName: "Nestaway Technologies",
    siteId: "site_nest_001",
    siteName: "Nestaway Koramangala, Bangalore",
    ipAddress: "10.25.20.35",
    userType: "customer",
    category: "Maintenance",
    severity: "info",
    status: "success",
  },

  // --- Co-Living Segment: Stanza Living ---
  {
    id: "log_054",
    timestamp: "2024-01-15T07:45:00",
    user: "Deepak Jain",
    userRole: "IT Head",
    action: "qos_policy_updated",
    description: "Updated QoS policy to prioritize video streaming during evening hours",
    customerId: "cust_007",
    customerName: "Stanza Living",
    siteId: null,
    siteName: null,
    ipAddress: "10.35.10.5",
    userType: "customer",
    category: "Policy Management",
    severity: "info",
    status: "success",
  },
  {
    id: "log_055",
    timestamp: "2024-01-15T07:30:00",
    user: "System",
    userRole: "Automated",
    action: "fair_usage_alert",
    description: "12 residents exceeded daily fair usage limit",
    customerId: "cust_007",
    customerName: "Stanza Living",
    siteId: "site_010",
    siteName: "Stanza Living Berlin, Bangalore",
    ipAddress: null,
    userType: "internal",
    category: "Monitoring",
    severity: "info",
    status: "triggered",
  },

  // --- PG Segment: Zolo Stays ---
  {
    id: "log_056",
    timestamp: "2024-01-15T07:15:00",
    user: "Nikhil Reddy",
    userRole: "Manager",
    action: "resident_checkout",
    description: "Processed WiFi deactivation for 45 checked-out residents",
    customerId: "cust_004",
    customerName: "Zolo Stays",
    siteId: null,
    siteName: null,
    ipAddress: "10.15.10.20",
    userType: "customer",
    category: "User Management",
    severity: "info",
    status: "success",
  },
  {
    id: "log_057",
    timestamp: "2024-01-15T07:00:00",
    user: "Vikram Singh",
    userRole: "Deployment Engineer",
    action: "bulk_site_config",
    description: "Applied standard configuration to 15 new Zolo properties",
    customerId: "cust_004",
    customerName: "Zolo Stays",
    siteId: null,
    siteName: null,
    ipAddress: "192.168.1.108",
    userType: "internal",
    category: "Configuration",
    severity: "info",
    status: "success",
  },
  {
    id: "log_058",
    timestamp: "2024-01-14T23:45:00",
    user: "System",
    userRole: "Automated",
    action: "site_offline_alert",
    description: "Critical: Site went offline due to power outage",
    customerId: "cust_004",
    customerName: "Zolo Stays",
    siteId: "site_zolo_045",
    siteName: "Zolo Crown, Whitefield, Bangalore",
    ipAddress: null,
    userType: "internal",
    category: "Monitoring",
    severity: "critical",
    status: "triggered",
  },

  // --- Hotel Segment: OYO Rooms ---
  {
    id: "log_059",
    timestamp: "2024-01-14T22:30:00",
    user: "Rohit Kapoor",
    userRole: "IT Director",
    action: "integration_api_updated",
    description: "Updated OYO booking system integration API endpoints",
    customerId: "cust_008",
    customerName: "OYO Rooms",
    siteId: null,
    siteName: null,
    ipAddress: "10.55.10.5",
    userType: "customer",
    category: "Auth Configuration",
    severity: "info",
    status: "success",
  },
  {
    id: "log_060",
    timestamp: "2024-01-14T21:15:00",
    user: "System",
    userRole: "Automated",
    action: "mass_site_update",
    description: "Applied security patch to 180 OYO properties",
    customerId: "cust_008",
    customerName: "OYO Rooms",
    siteId: null,
    siteName: null,
    ipAddress: null,
    userType: "internal",
    category: "Maintenance",
    severity: "info",
    status: "success",
  },

  // --- Hotel Segment: Treebo Hotels ---
  {
    id: "log_061",
    timestamp: "2024-01-14T20:00:00",
    user: "Meera Nair",
    userRole: "Admin",
    action: "guest_feedback_enabled",
    description: "Enabled WiFi satisfaction survey on captive portal",
    customerId: "cust_009",
    customerName: "Treebo Hotels",
    siteId: null,
    siteName: null,
    ipAddress: "10.48.10.15",
    userType: "customer",
    category: "Configuration",
    severity: "info",
    status: "success",
  },
  {
    id: "log_062",
    timestamp: "2024-01-14T19:30:00",
    user: "Priya Sharma",
    userRole: "Support Engineer",
    action: "ticket_resolved",
    description: "Resolved intermittent connectivity issue - replaced faulty switch",
    customerId: "cust_009",
    customerName: "Treebo Hotels",
    siteId: "site_treebo_012",
    siteName: "Treebo Trend Lavanya, Pune",
    ipAddress: "192.168.1.105",
    userType: "internal",
    category: "Support",
    severity: "info",
    status: "success",
  },

  // --- Authentication Events ---
  {
    id: "log_063",
    timestamp: "2024-01-14T18:45:00",
    user: "Unknown",
    userRole: "N/A",
    action: "brute_force_detected",
    description: "Blocked IP after 10 failed login attempts",
    customerId: "cust_002",
    customerName: "WeWork India",
    siteId: "site_004",
    siteName: "WeWork Galaxy, Bangalore",
    ipAddress: "45.33.32.156",
    userType: "customer",
    category: "Security",
    severity: "critical",
    status: "blocked",
  },
  {
    id: "log_064",
    timestamp: "2024-01-14T18:30:00",
    user: "Vikram Singh",
    userRole: "Super Admin",
    action: "admin_password_reset",
    description: "Reset password for customer admin account",
    customerId: "cust_003",
    customerName: "Nestaway Technologies",
    siteId: null,
    siteName: null,
    ipAddress: "192.168.1.108",
    userType: "internal",
    category: "User Management",
    severity: "info",
    status: "success",
  },

  // --- System Events ---
  {
    id: "log_065",
    timestamp: "2024-01-14T18:00:00",
    user: "System",
    userRole: "Automated",
    action: "database_maintenance",
    description: "Completed weekly database optimization and indexing",
    customerId: null,
    customerName: null,
    siteId: null,
    siteName: null,
    ipAddress: null,
    userType: "internal",
    category: "System",
    severity: "info",
    status: "success",
  },
  {
    id: "log_066",
    timestamp: "2024-01-14T17:45:00",
    user: "System",
    userRole: "Automated",
    action: "api_rate_limit_exceeded",
    description: "API rate limit exceeded for third-party integration",
    customerId: "cust_010",
    customerName: "Tata Consultancy Services",
    siteId: null,
    siteName: null,
    ipAddress: null,
    userType: "internal",
    category: "System",
    severity: "warning",
    status: "triggered",
  },

  // --- Billing/License Events ---
  {
    id: "log_067",
    timestamp: "2024-01-14T17:30:00",
    user: "Anita Desai",
    userRole: "Account Manager",
    action: "invoice_generated",
    description: "Generated monthly invoice for Q4 2023",
    customerId: "cust_007",
    customerName: "Stanza Living",
    siteId: null,
    siteName: null,
    ipAddress: "192.168.1.101",
    userType: "internal",
    category: "License Management",
    severity: "info",
    status: "success",
  },
  {
    id: "log_068",
    timestamp: "2024-01-14T17:15:00",
    user: "System",
    userRole: "Automated",
    action: "license_expiry_warning",
    description: "License expiring in 45 days - renewal required",
    customerId: "cust_002",
    customerName: "WeWork India",
    siteId: null,
    siteName: null,
    ipAddress: null,
    userType: "internal",
    category: "License Management",
    severity: "warning",
    status: "pending",
  },

  // --- Device Management Events ---
  {
    id: "log_069",
    timestamp: "2024-01-14T17:00:00",
    user: "Ravi Kumar",
    userRole: "Support Engineer",
    action: "ap_replaced",
    description: "Replaced faulty Ruckus R650 AP with new unit",
    customerId: "cust_001",
    customerName: "Oberoi Hotels & Resorts",
    siteId: "site_002",
    siteName: "The Oberoi, Delhi",
    ipAddress: "192.168.1.112",
    userType: "internal",
    category: "Device Management",
    severity: "info",
    status: "success",
  },
  {
    id: "log_070",
    timestamp: "2024-01-14T16:45:00",
    user: "System",
    userRole: "Automated",
    action: "device_offline_alert",
    description: "5 APs went offline simultaneously - possible switch failure",
    customerId: "cust_006",
    customerName: "Awfis Space Solutions",
    siteId: "site_awfis_003",
    siteName: "Awfis Cyber Hub, Gurgaon",
    ipAddress: null,
    userType: "internal",
    category: "Monitoring",
    severity: "critical",
    status: "triggered",
  },

  // --- Customer Portal Events ---
  {
    id: "log_071",
    timestamp: "2024-01-14T16:30:00",
    user: "Deepak Jain",
    userRole: "IT Head",
    action: "report_exported",
    description: "Exported 6-month usage analytics report",
    customerId: "cust_007",
    customerName: "Stanza Living",
    siteId: null,
    siteName: null,
    ipAddress: "10.35.10.5",
    userType: "customer",
    category: "Reports",
    severity: "info",
    status: "success",
  },
  {
    id: "log_072",
    timestamp: "2024-01-14T16:15:00",
    user: "Sneha Patel",
    userRole: "Admin",
    action: "dashboard_customized",
    description: "Customized dashboard widgets for property managers",
    customerId: "cust_003",
    customerName: "Nestaway Technologies",
    siteId: null,
    siteName: null,
    ipAddress: "10.25.10.20",
    userType: "customer",
    category: "Configuration",
    severity: "info",
    status: "success",
  },

  // --- Internal Admin Events ---
  {
    id: "log_073",
    timestamp: "2024-01-14T16:00:00",
    user: "Priya Sharma",
    userRole: "Super Admin",
    action: "customer_impersonation",
    description: "Entered customer view mode for troubleshooting",
    customerId: "cust_004",
    customerName: "Zolo Stays",
    siteId: "site_zolo_023",
    siteName: "Zolo Athena, Gachibowli, Hyderabad",
    ipAddress: "192.168.1.105",
    userType: "internal",
    category: "User Management",
    severity: "info",
    status: "success",
  },
  {
    id: "log_074",
    timestamp: "2024-01-14T15:45:00",
    user: "Rahul Mehta",
    userRole: "Deployment Engineer",
    action: "template_updated",
    description: "Updated Co-Working Standard configuration template",
    customerId: null,
    customerName: null,
    siteId: null,
    siteName: null,
    ipAddress: "192.168.1.110",
    userType: "internal",
    category: "Configuration",
    severity: "info",
    status: "success",
  },

  // --- More Customer Activities ---
  {
    id: "log_075",
    timestamp: "2024-01-14T15:30:00",
    user: "Amit Verma",
    userRole: "Network Admin",
    action: "network_segmented",
    description: "Created new VLAN for startup tenant isolation",
    customerId: "cust_002",
    customerName: "WeWork India",
    siteId: "site_wework_006",
    siteName: "WeWork Worli, Mumbai",
    ipAddress: "10.30.30.15",
    userType: "customer",
    category: "Configuration",
    severity: "info",
    status: "success",
  },
  {
    id: "log_076",
    timestamp: "2024-01-14T15:15:00",
    user: "Suresh Menon",
    userRole: "IT Director",
    action: "scheduled_report_created",
    description: "Set up daily executive summary email for management",
    customerId: "cust_005",
    customerName: "ITC Hotels",
    siteId: null,
    siteName: null,
    ipAddress: "10.20.10.5",
    userType: "customer",
    category: "Reports",
    severity: "info",
    status: "success",
  },
  {
    id: "log_077",
    timestamp: "2024-01-14T15:00:00",
    user: "Venkat Raghavan",
    userRole: "IT Admin",
    action: "access_revoked",
    description: "Revoked WiFi access for 12 terminated employees",
    customerId: "cust_010",
    customerName: "Tata Consultancy Services",
    siteId: "site_tcs_001",
    siteName: "TCS Siruseri, Chennai",
    ipAddress: "10.45.20.15",
    userType: "customer",
    category: "User Management",
    severity: "info",
    status: "success",
  },

  // --- Recent Internal Operations ---
  {
    id: "log_078",
    timestamp: "2024-01-14T14:45:00",
    user: "Anita Desai",
    userRole: "Account Manager",
    action: "customer_created",
    description: "Onboarded new customer: Prestige Estates Projects",
    customerId: "cust_new_001",
    customerName: "Prestige Estates Projects",
    siteId: null,
    siteName: null,
    ipAddress: "192.168.1.101",
    userType: "internal",
    category: "Site Management",
    severity: "info",
    status: "success",
  },
  {
    id: "log_079",
    timestamp: "2024-01-14T14:30:00",
    user: "Vikram Singh",
    userRole: "Deployment Engineer",
    action: "site_decommissioned",
    description: "Decommissioned site after lease termination",
    customerId: "cust_003",
    customerName: "Nestaway Technologies",
    siteId: "site_nest_old_001",
    siteName: "Nestaway Indiranagar (Closed)",
    ipAddress: "192.168.1.108",
    userType: "internal",
    category: "Site Management",
    severity: "info",
    status: "success",
  },
  {
    id: "log_080",
    timestamp: "2024-01-14T14:15:00",
    user: "System",
    userRole: "Automated",
    action: "health_check_completed",
    description: "Hourly platform health check - all systems operational",
    customerId: null,
    customerName: null,
    siteId: null,
    siteName: null,
    ipAddress: null,
    userType: "internal",
    category: "System",
    severity: "info",
    status: "success",
  },
];

/**
 * Configuration Templates
 */
export const configTemplates = [
  {
    id: "tmpl_001",
    name: "Hotel Premium",
    type: "Hotel",
    tier: "Premium",
    description: "Standard configuration for premium hotel properties",
    settings: {
      bandwidthPerUser: 10, // Mbps
      maxDevicesPerUser: 5,
      sessionTimeout: 1440, // minutes
      captivePortal: true,
      guestNetwork: true,
      vlanSegmentation: true,
      qosEnabled: true,
      firewallRules: "strict",
    },
    usedBy: 20,
    lastModified: "2024-01-10",
  },
  {
    id: "tmpl_002",
    name: "Co-Working Standard",
    type: "Co-Working",
    tier: "Standard",
    description: "Configuration for standard co-working spaces",
    settings: {
      bandwidthPerUser: 15,
      maxDevicesPerUser: 3,
      sessionTimeout: 720,
      captivePortal: true,
      guestNetwork: true,
      vlanSegmentation: true,
      qosEnabled: true,
      firewallRules: "moderate",
    },
    usedBy: 35,
    lastModified: "2024-01-08",
  },
  {
    id: "tmpl_003",
    name: "PG Basic",
    type: "PG",
    tier: "Basic",
    description: "Basic configuration for PG accommodations",
    settings: {
      bandwidthPerUser: 5,
      maxDevicesPerUser: 2,
      sessionTimeout: 1440,
      captivePortal: true,
      guestNetwork: false,
      vlanSegmentation: false,
      qosEnabled: false,
      firewallRules: "basic",
    },
    usedBy: 120,
    lastModified: "2024-01-05",
  },
  {
    id: "tmpl_004",
    name: "Co-Living Premium",
    type: "Co-Living",
    tier: "Premium",
    description: "Premium configuration for co-living properties",
    settings: {
      bandwidthPerUser: 8,
      maxDevicesPerUser: 4,
      sessionTimeout: 2880,
      captivePortal: true,
      guestNetwork: true,
      vlanSegmentation: true,
      qosEnabled: true,
      firewallRules: "moderate",
    },
    usedBy: 85,
    lastModified: "2024-01-12",
  },
];

/**
 * Helper functions
 */
export const getCustomerById = (id) => customers.find((c) => c.id === id);
export const getSiteById = (id) => sites.find((s) => s.id === id);
export const getSitesByCustomer = (customerId) => sites.filter((s) => s.customerId === customerId);
export const getAlertsByCustomer = (customerId) => systemAlerts.filter((a) => a.customerId === customerId);
export const getAlertsBySite = (siteId) => systemAlerts.filter((a) => a.siteId === siteId);
export const getTicketsByCustomer = (customerId) => supportTickets.filter((t) => t.customerId === customerId);
export const getLicenseByCustomer = (customerId) => licenses.find((l) => l.customerId === customerId);

export const getSiteStatusCounts = () => {
  const counts = { online: 0, degraded: 0, offline: 0, maintenance: 0 };
  sites.forEach((site) => {
    if (counts[site.status] !== undefined) {
      counts[site.status]++;
    }
  });
  return counts;
};

export const getAlertCounts = () => {
  const counts = { critical: 0, warning: 0, info: 0 };
  systemAlerts.forEach((alert) => {
    if (counts[alert.type] !== undefined) {
      counts[alert.type]++;
    }
  });
  return counts;
};

/**
 * Recent Activities / Audit Logs
 */
export const recentActivities = [
  {
    id: "act_001",
    type: "site_provisioned",
    action: "Site Provisioned",
    description: "New site 'Oberoi Grand - Ballroom Wing' provisioned",
    user: "Priya Sharma",
    userRole: "Support Engineer",
    customerId: "cust_001",
    customerName: "Oberoi Hotels & Resorts",
    siteId: "site_001",
    siteName: "Oberoi Grand - Ballroom Wing",
    timestamp: "2024-01-15T14:32:00Z",
    status: "success",
    details: { bandwidth: 1000, users: 500 },
  },
  {
    id: "act_002",
    type: "config_updated",
    action: "Configuration Updated",
    description: "Bandwidth limit increased for WeWork Cyber Hub",
    user: "Rahul Mehta",
    userRole: "Deployment Engineer",
    customerId: "cust_002",
    customerName: "WeWork India",
    siteId: "site_006",
    siteName: "WeWork Cyber Hub",
    timestamp: "2024-01-15T13:15:00Z",
    status: "success",
    details: { oldBandwidth: 500, newBandwidth: 1000 },
  },
  {
    id: "act_003",
    type: "alert_resolved",
    action: "Alert Resolved",
    description: "Critical connectivity alert resolved for Zolo HSR Layout",
    user: "Vikram Singh",
    userRole: "Support Engineer",
    customerId: "cust_004",
    customerName: "Zolo Stays",
    siteId: "site_012",
    siteName: "Zolo HSR Layout",
    timestamp: "2024-01-15T11:45:00Z",
    status: "success",
    details: { alertId: "alert_003", resolution: "Router restarted" },
  },
  {
    id: "act_004",
    type: "user_added",
    action: "User Added",
    description: "New admin user added for Nestaway Technologies",
    user: "Anita Desai",
    userRole: "Super Admin",
    customerId: "cust_003",
    customerName: "Nestaway Technologies",
    siteId: null,
    siteName: null,
    timestamp: "2024-01-15T10:20:00Z",
    status: "success",
    details: { newUser: "Rohan Joshi", role: "Admin" },
  },
  {
    id: "act_005",
    type: "site_offline",
    action: "Site Went Offline",
    description: "Stanza Living Koramangala went offline",
    user: "System",
    userRole: "Automated",
    customerId: "cust_007",
    customerName: "Stanza Living",
    siteId: "site_021",
    siteName: "Stanza Living Koramangala",
    timestamp: "2024-01-15T09:30:00Z",
    status: "warning",
    details: { reason: "Power outage detected" },
  },
  {
    id: "act_006",
    type: "ticket_created",
    action: "Support Ticket Created",
    description: "High priority ticket created for ITC Grand Chola",
    user: "System",
    userRole: "Automated",
    customerId: "cust_005",
    customerName: "ITC Hotels",
    siteId: "site_015",
    siteName: "ITC Grand Chola",
    timestamp: "2024-01-15T08:55:00Z",
    status: "info",
    details: { ticketId: "TKT-2024-0045", priority: "high" },
  },
  {
    id: "act_007",
    type: "license_renewed",
    action: "License Renewed",
    description: "Enterprise license renewed for Awfis Space Solutions",
    user: "Priya Sharma",
    userRole: "Super Admin",
    customerId: "cust_006",
    customerName: "Awfis Space Solutions",
    siteId: null,
    siteName: null,
    timestamp: "2024-01-14T16:40:00Z",
    status: "success",
    details: { validUntil: "2026-02-14", users: 15000 },
  },
  {
    id: "act_008",
    type: "maintenance_scheduled",
    action: "Maintenance Scheduled",
    description: "Scheduled maintenance for CoHo Living sites",
    user: "Rahul Mehta",
    userRole: "Deployment Engineer",
    customerId: "cust_009",
    customerName: "CoHo Living",
    siteId: null,
    siteName: "All Sites",
    timestamp: "2024-01-14T15:10:00Z",
    status: "info",
    details: { scheduledFor: "2024-01-20T02:00:00Z", duration: "4 hours" },
  },
  {
    id: "act_009",
    type: "policy_updated",
    action: "Policy Updated",
    description: "Guest access policy updated for Lemon Tree Hotels",
    user: "Vikram Singh",
    userRole: "Support Engineer",
    customerId: "cust_010",
    customerName: "Lemon Tree Hotels",
    siteId: null,
    siteName: null,
    timestamp: "2024-01-14T14:25:00Z",
    status: "success",
    details: { policyName: "Guest WiFi Access", change: "Session timeout increased" },
  },
  {
    id: "act_010",
    type: "backup_completed",
    action: "Backup Completed",
    description: "Daily configuration backup completed",
    user: "System",
    userRole: "Automated",
    customerId: null,
    customerName: null,
    siteId: null,
    siteName: null,
    timestamp: "2024-01-14T03:00:00Z",
    status: "success",
    details: { backupSize: "2.4 GB", sites: 256 },
  },
  {
    id: "act_011",
    type: "firmware_update",
    action: "Firmware Updated",
    description: "Firmware update deployed to 45 sites",
    user: "Rahul Mehta",
    userRole: "Deployment Engineer",
    customerId: null,
    customerName: "Multiple Customers",
    siteId: null,
    siteName: "45 Sites",
    timestamp: "2024-01-13T22:30:00Z",
    status: "success",
    details: { version: "2.4.1", affectedDevices: 890 },
  },
  {
    id: "act_012",
    type: "security_alert",
    action: "Security Alert",
    description: "Unusual login activity detected",
    user: "System",
    userRole: "Automated",
    customerId: "cust_002",
    customerName: "WeWork India",
    siteId: "site_007",
    siteName: "WeWork BKC Mumbai",
    timestamp: "2024-01-13T19:15:00Z",
    status: "warning",
    details: { attempts: 15, ipAddress: "103.25.xx.xx" },
  },
];

export const getRecentActivities = (limit = 10) => {
  return recentActivities.slice(0, limit);
};

export const getActivitiesByCustomer = (customerId) => {
  return recentActivities.filter(a => a.customerId === customerId);
};

export const getActivitiesBySite = (siteId) => {
  return recentActivities.filter(a => a.siteId === siteId);
};
