// src/constants/sampleUsers.js

const sampleUsers = [
  // Enterprise - Mumbai Corporate Office
  {
    id: "USER001",
    firstName: "Amit",
    lastName: "Sharma",
    mobile: "+91-9876543210",
    email: "amit.sharma@mail.com",
    userPolicy: { speed: "Upto 10 Mbps", dataVolume: "50 GB", deviceLimit: "3", dataCycleType: "Monthly" },
    devicesCount: 3,
    status: "Active",
    registration: "2024-01-15",
    lastOnline: "2 min ago",
    usageTotalData: "15.2 GB",
    usageSessions: 47,
    usageAvgSession: "3h 25m",
    usageLastOnline: "2 min ago",
    location: "Mumbai, Maharashtra",
    segment: "enterprise",
    siteName: "Mumbai Corporate Office",
    siteId: "SITE-MUM-ENT-001",
    employeeId: "E123",
    department: "Finance",
    userCategory: "employee",
    password: "387425",
  },
  {
    id: "USER011",
    firstName: "Ravi",
    lastName: "Kumar",
    mobile: "+91-9876543201",
    email: "ravi.kumar@mail.com",
    userPolicy: { speed: "Upto 25 Mbps", dataVolume: "100 GB", deviceLimit: "5", dataCycleType: "Monthly" },
    devicesCount: 4,
    status: "Active",
    registration: "2024-04-15",
    lastOnline: "1 hour ago",
    usageTotalData: "46.3 GB",
    usageSessions: 55,
    usageAvgSession: "2h 18m",
    usageLastOnline: "1 hour ago",
    location: "Mumbai, Maharashtra",
    segment: "enterprise",
    siteName: "Mumbai Corporate Office",
    siteId: "SITE-MUM-ENT-001",
    employeeId: "E124",
    department: "Operations",
    userCategory: "employee",
    password: "582641",
  },
  {
    id: "USER012",
    firstName: "Neeta",
    lastName: "Singh",
    mobile: "+91-9876543222",
    email: "neeta.singh@mail.com",
    userPolicy: { speed: "Upto 50 Mbps", dataVolume: "200 GB", deviceLimit: "4", dataCycleType: "Monthly" },
    devicesCount: 7,
    status: "Active",
    registration: "2024-06-15",
    lastOnline: "30 min ago",
    usageTotalData: "82.4 GB",
    usageSessions: 81,
    usageAvgSession: "4h 09m",
    usageLastOnline: "30 min ago",
    location: "Mumbai, Maharashtra",
    segment: "enterprise",
    siteName: "Mumbai Corporate Office",
    siteId: "SITE-MUM-ENT-001",
    employeeId: "E125",
    department: "Sales",
    userCategory: "employee",
    password: "741258",
  },
  
  // CoLiving - Spectra Urban Living - Bangalore
  {
    id: "USER003",
    firstName: "Rajesh",
    lastName: "Kumar",
    mobile: "+91-9988776655",
    email: "",
    userPolicy: { speed: "Upto 10 Mbps", dataVolume: "50 GB", deviceLimit: "1", dataCycleType: "Monthly" },
    devicesCount: 1,
    status: "Suspended",
    registration: "2024-02-20",
    lastOnline: "1 hour ago",
    usageTotalData: "8.7 GB",
    usageSessions: 13,
    usageAvgSession: "2h 00m",
    usageLastOnline: "1 hour ago",
    location: "Bangalore, Karnataka",
    segment: "coLiving",
    siteName: "Spectra Urban Living - Bangalore",
    siteId: "SITE-BLR-COL-002",
    residentType: "Tenant",
    roomNumber: "101A",
    userCategory: "resident",
    password: "529834",
  },
  {
    id: "USER013",
    firstName: "Anita",
    lastName: "Shah",
    mobile: "+91-9988776656",
    email: "",
    userPolicy: { speed: "Upto 15 Mbps", dataVolume: "75 GB", deviceLimit: "2", dataCycleType: "Monthly" },
    devicesCount: 2,
    status: "Active",
    registration: "2024-03-20",
    lastOnline: "20 min ago",
    usageTotalData: "49.2 GB",
    usageSessions: 89,
    usageAvgSession: "2h 44m",
    usageLastOnline: "20 min ago",
    location: "Bangalore, Karnataka",
    segment: "coLiving",
    siteName: "Spectra Urban Living - Bangalore",
    siteId: "SITE-BLR-COL-002",
    residentType: "Owner",
    roomNumber: "202B",
    userCategory: "resident",
    password: "346872",
  },
  {
    id: "USER014",
    firstName: "Vipin",
    lastName: "Nair",
    mobile: "+91-9988776657",
    email: "",
    userPolicy: { speed: "Upto 20 Mbps", dataVolume: "90 GB", deviceLimit: "3", dataCycleType: "Monthly" },
    devicesCount: 3,
    status: "Active",
    registration: "2024-04-22",
    lastOnline: "15 min ago",
    usageTotalData: "61.5 GB",
    usageSessions: 72,
    usageAvgSession: "3h 10m",
    usageLastOnline: "15 min ago",
    location: "Bangalore, Karnataka",
    segment: "coLiving",
    siteName: "Spectra Urban Living - Bangalore",
    siteId: "SITE-BLR-COL-002",
    residentType: "Tenant",
    roomNumber: "303C",
    userCategory: "resident",
    password: "192847",
  },
  
  // CoWorking - Spectra WorkHub - Pune
  {
    id: "USER005",
    firstName: "Sanjay",
    lastName: "Rao",
    mobile: "+91-9012345678",
    email: "",
    userPolicy: { speed: "Upto 10 Mbps", dataVolume: "50 GB", deviceLimit: "1", dataCycleType: "Monthly" },
    devicesCount: 1,
    status: "Blocked",
    registration: "2024-03-01",
    lastOnline: "2 days ago",
    usageTotalData: "20.2 GB",
    usageSessions: 15,
    usageAvgSession: "1h 32m",
    usageLastOnline: "2 days ago",
    location: "Pune, Maharashtra",
    segment: "coWorking",
    siteName: "Spectra WorkHub - Pune",
    siteId: "SITE-PUN-COW-003",
    companyName: "Tech Solutions",
    deskNumber: "D12",
    userCategory: "member",
    password: "918352",
  },
  {
    id: "USER015",
    firstName: "Suresh",
    lastName: "Kumar",
    mobile: "+91-9012345679",
    email: "suresh.kumar@mail.com",
    userPolicy: { speed: "Upto 15 Mbps", dataVolume: "75 GB", deviceLimit: "2", dataCycleType: "Monthly" },
    devicesCount: 2,
    status: "Active",
    registration: "2024-05-01",
    lastOnline: "1 hour ago",
    usageTotalData: "31.6 GB",
    usageSessions: 41,
    usageAvgSession: "2h 05m",
    usageLastOnline: "1 hour ago",
    location: "Pune, Maharashtra",
    segment: "coWorking",
    siteName: "Spectra WorkHub - Pune",
    siteId: "SITE-PUN-COW-003",
    companyName: "StartUp India",
    deskNumber: "A5",
    userCategory: "member",
    password: "658374",
  },
  {
    id: "USER016",
    firstName: "Pooja",
    lastName: "Joshi",
    mobile: "+91-9012345680",
    email: "pooja.joshi@mail.com",
    userPolicy: { speed: "Upto 20 Mbps", dataVolume: "100 GB", deviceLimit: "3", dataCycleType: "Monthly" },
    devicesCount: 3,
    status: "Active",
    registration: "2024-06-20",
    lastOnline: "30 min ago",
    usageTotalData: "90.8 GB",
    usageSessions: 58,
    usageAvgSession: "4h 15m",
    usageLastOnline: "30 min ago",
    location: "Pune, Maharashtra",
    segment: "coWorking",
    siteName: "Spectra WorkHub - Pune",
    siteId: "SITE-PUN-COW-003",
    companyName: "Freelancers Ltd",
    deskNumber: "C12",
    userCategory: "member",
    password: "487392",
  },
  
  // Hotel - Spectra Grand Hotel - Goa
  {
    id: "USER007",
    firstName: "Vikram",
    lastName: "Chatterjee",
    mobile: "+91-9988123456",
    email: "",
    userPolicy: { speed: "Upto 10 Mbps", dataVolume: "50 GB", deviceLimit: "1", dataCycleType: "Daily" },
    devicesCount: 1,
    status: "Active",
    registration: "2024-03-15",
    lastOnline: "12 min ago",
    usageTotalData: "5.8 GB",
    usageSessions: 7,
    usageAvgSession: "0h 41m",
    usageLastOnline: "12 min ago",
    location: "Goa",
    segment: "hotel",
    siteName: "Spectra Grand Hotel - Goa",
    siteId: "SITE-GOA-HTL-004",
    roomNumber: "305",
    floor: "3",
    checkInDate: "2025-09-01",
    checkOutDate: "2025-09-07",
    userCategory: "guest",
    password: "296153",
  },
  {
    id: "USER017",
    firstName: "Ramesh",
    lastName: "Iyer",
    mobile: "+91-9988123457",
    email: "",
    userPolicy: { speed: "Upto 15 Mbps", dataVolume: "70 GB", deviceLimit: "2", dataCycleType: "Daily" },
    devicesCount: 2,
    status: "Active",
    registration: "2024-04-18",
    lastOnline: "10 min ago",
    usageTotalData: "12.2 GB",
    usageSessions: 18,
    usageAvgSession: "1h 22m",
    usageLastOnline: "10 min ago",
    location: "Goa",
    segment: "hotel",
    siteName: "Spectra Grand Hotel - Goa",
    siteId: "SITE-GOA-HTL-004",
    roomNumber: "312",
    floor: "3",
    checkInDate: "2025-10-01",
    checkOutDate: "2025-10-15",
    userCategory: "guest",
    password: "714589",
  },
  {
    id: "USER018",
    firstName: "Anita",
    lastName: "Kapoor",
    mobile: "+91-9988123458",
    email: "",
    userPolicy: { speed: "Upto 20 Mbps", dataVolume: "100 GB", deviceLimit: "3", dataCycleType: "Daily" },
    devicesCount: 3,
    status: "Suspended",
    registration: "2024-05-25",
    lastOnline: "1 hour ago",
    usageTotalData: "21.9 GB",
    usageSessions: 33,
    usageAvgSession: "1h 47m",
    usageLastOnline: "1 hour ago",
    location: "Goa",
    segment: "hotel",
    siteName: "Spectra Grand Hotel - Goa",
    siteId: "SITE-GOA-HTL-004",
    roomNumber: "320",
    floor: "3",
    checkInDate: "2025-11-05",
    checkOutDate: "2025-11-10",
    userCategory: "guest",
    password: "829163",
  },
  
  // PG - Spectra PG Residency - Chennai
  {
    id: "USER008",
    firstName: "Divya",
    lastName: "Nair",
    mobile: "+91-9876541230",
    email: "",
    userPolicy: { speed: "Upto 25 Mbps", dataVolume: "100 GB", deviceLimit: "4", dataCycleType: "Monthly" },
    devicesCount: 4,
    status: "Suspended",
    registration: "2024-03-12",
    lastOnline: "3 hours ago",
    usageTotalData: "40.4 GB",
    usageSessions: 64,
    usageAvgSession: "2h 41m",
    usageLastOnline: "3 hours ago",
    location: "Chennai, Tamil Nadu",
    segment: "pg",
    siteName: "Spectra PG Residency - Chennai",
    siteId: "SITE-CHN-PGR-005",
    pgType: "Female",
    roomNumber: "B12",
    userCategory: "resident",
    password: "837492",
  },
  {
    id: "USER019",
    firstName: "Sita",
    lastName: "Kumari",
    mobile: "+91-9876541231",
    email: "",
    userPolicy: { speed: "Upto 15 Mbps", dataVolume: "75 GB", deviceLimit: "2", dataCycleType: "Monthly" },
    devicesCount: 2,
    status: "Active",
    registration: "2024-06-20",
    lastOnline: "45 min ago",
    usageTotalData: "24.9 GB",
    usageSessions: 32,
    usageAvgSession: "1h 54m",
    usageLastOnline: "45 min ago",
    location: "Chennai, Tamil Nadu",
    segment: "pg",
    siteName: "Spectra PG Residency - Chennai",
    siteId: "SITE-CHN-PGR-005",
    pgType: "Male",
    roomNumber: "B15",
    userCategory: "resident",
    password: "481726",
  },
  {
    id: "USER020",
    firstName: "Kiran",
    lastName: "Sharma",
    mobile: "+91-9876541232",
    email: "",
    userPolicy: { speed: "Upto 10 Mbps", dataVolume: "50 GB", deviceLimit: "1", dataCycleType: "Monthly" },
    devicesCount: 1,
    status: "Active",
    registration: "2024-06-25",
    lastOnline: "30 min ago",
    usageTotalData: "12.1 GB",
    usageSessions: 24,
    usageAvgSession: "1h 17m",
    usageLastOnline: "30 min ago",
    location: "Chennai, Tamil Nadu",
    segment: "pg",
    siteName: "Spectra PG Residency - Chennai",
    siteId: "SITE-CHN-PGR-005",
    pgType: "Female",
    roomNumber: "B18",
    userCategory: "resident",
    password: "536718",
  },
  
  // Miscellaneous - Spectra Community Hub - Delhi
  {
    id: "USER009",
    firstName: "Rahul",
    lastName: "Desai",
    mobile: "+91-9098765432",
    email: "rahul.desai@mail.com",
    userPolicy: { speed: "Upto 50 Mbps", dataVolume: "100 GB", deviceLimit: "6", dataCycleType: "Monthly" },
    devicesCount: 6,
    status: "Active",
    registration: "2024-03-17",
    lastOnline: "30 sec ago",
    usageTotalData: "77.0 GB",
    usageSessions: 110,
    usageAvgSession: "3h 34m",
    usageLastOnline: "30 sec ago",
    location: "Delhi",
    segment: "miscellaneous",
    siteName: "Spectra Community Hub - Delhi",
    siteId: "SITE-DEL-MIS-006",
    notes: "VIP",
    userCategory: "user",
    password: "194756",
  },
  {
    id: "USER021",
    firstName: "Neelam",
    lastName: "Patel",
    mobile: "+91-9098765433",
    email: "neelam.patel@mail.com",
    userPolicy: { speed: "Upto 20 Mbps", dataVolume: "80 GB", deviceLimit: "3", dataCycleType: "Monthly" },
    devicesCount: 3,
    status: "Active",
    registration: "2024-04-20",
    lastOnline: "10 min ago",
    usageTotalData: "35.5 GB",
    usageSessions: 60,
    usageAvgSession: "2h 52m",
    usageLastOnline: "10 min ago",
    location: "Delhi",
    segment: "miscellaneous",
    siteName: "Spectra Community Hub - Delhi",
    siteId: "SITE-DEL-MIS-006",
    notes: "Regular",
    userCategory: "user",
    password: "615283",
  },
  {
    id: "USER022",
    firstName: "Raja",
    lastName: "Singh",
    mobile: "+91-9098765434",
    email: "raja.singh@mail.com",
    userPolicy: { speed: "Upto 10 Mbps", dataVolume: "10 GB", deviceLimit: "1", dataCycleType: "Monthly" },
    devicesCount: 1,
    status: "Suspended",
    registration: "2024-05-20",
    lastOnline: "15 min ago",
    usageTotalData: "2.9 GB",
    usageSessions: 11,
    usageAvgSession: "1h 02m",
    usageLastOnline: "15 min ago",
    location: "Delhi",
    segment: "miscellaneous",
    siteName: "Spectra Community Hub - Delhi",
    siteId: "SITE-DEL-MIS-006",
    notes: "Inactive",
    userCategory: "user",
    password: "789145",
  }
];

export default sampleUsers;