// src/constants/userSampleData.js

/**
 * Centralized User Sample Data - API Format Aligned
 *
 * ALIGNMENT STATUS:
 * - Structure aligned with Sample API (wifi portal).docx format
 * - Response wrapper pattern applied where appropriate
 * - Field naming follows API conventions
 *
 * MissingForAPI:
 * - can_id (CAN ID from AAA system) - Backend to provide
 * - whp_alert (WhatsApp alert preference) - Backend to provide
 * - dataCycleResetDate (Next reset date) - Backend to calculate
 * - dataCycle (Current cycle period) - Backend to calculate
 * - totalVolumeInMB (Policy volume in MB) - Backend to provide
 * - totalDataConsumed_nonFupInMB - Backend to calculate from sessions
 * - totalDataConsumed_FupInMB - Backend to calculate if FUP applied
 * - currentSession (Live session data) - Backend to provide from NAS
 * - data_topup, speed_topup, plan_topup, device_topup - Backend to track
 * - scpLink (Self-care portal link) - Backend to generate
 * - fupStatus (Fair Usage Policy status) - Backend to determine
 * - trimScpLink (Base64 encoded link) - Backend to generate
 * - stnUserfind (STN user mapping) - Backend to provide if applicable
 *
 * FrontendOnly:
 * - segment (UI categorization)
 * - siteName, siteId (Frontend display context)
 * - userCategory (Frontend grouping)
 * - usageTotalData, usageSessions, usageAvgSession (Computed from sessions)
 * - lastOnline (Friendly time format)
 * - Segment-specific fields (employeeId, department, residentType, etc.)
 */

import * as reportGen from '../utils/reportDataGenerator';

/**
 * Convert portal user data to API format
 * @param {object} user - Portal user object
 * @returns {object} API-formatted user response
 */
export const convertUserToAPIFormat = (user) => {
  return {
    user_id: user.mobile || user.id,
    account_id: `${user.siteId?.split('-')[0]}-${user.mobile || user.id}`,
    domain_id: user.siteId || "UNKNOWN_SITE",
    site_name: user.siteName || "Unknown Site",
    f_name: user.firstName,
    l_name: user.lastName,
    mobile: user.mobile,
    email: user.email || "",
    device_count: String(user.devicesCount || 0),
    status: user.status,
    pkg_id: user.userPolicy?.policyId || "POLICY_UNKNOWN",
    speedname: user.userPolicy?.speed || "Unknown",
    // Missing from portal - to be provided by backend
    can_id: "", // Backend to provide
    whp_alert: "Y", // Backend to provide
    dataCycleResetDate: "", // Backend to calculate
    dataCycle: "", // Backend to calculate
    totalVolumeInMB: 0, // Backend to provide
    totalDataConsumed_nonFupInMB: 0, // Backend to calculate
    totalDataConsumed_FupInMB: "0", // Backend to calculate
    currentSession: [], // Backend to provide
    data_topup: "", // Backend to track
    speed_topup: "", // Backend to track
    plan_topup: "", // Backend to track
    device_topup: "", // Backend to track
    scpLink: "", // Backend to generate
    fupStatus: "Not Applied" // Backend to determine
  };
};

/**
 * Sample Users - Enhanced with API alignment
 * Retains all portal business data while documenting API gaps
 */
export const sampleUsers = [
  // Enterprise - Mumbai Corporate Office (fixed bandwidth site, max 200 Mbps)
  {
    id: "USER001",
    firstName: "Amit",
    lastName: "Sharma",
    mobile: "+91-9876543210",
    email: "amit.sharma@mail.com",
    policyId: "ENT_WIFI_10Mbps_50GB_3Devices_Monthly",
    speed: "Upto 10 Mbps",
    dataVolume: "50 GB",
    deviceLimit: "3",
    dataCycleType: "Monthly",
    dataResetDate: "2025-01-01", // Next data reset date
    devicesCount: 2,
    status: "Active",
    registration: "2024-01-15",
    lastOnline: "2 min ago",
    usageTotalData: "15.2 GB",
    usageSessions: 47,
    usageAvgSession: "3h 25m",
    usageLastOnline: "2 min ago",
    location: "Mumbai, Maharashtra",
    segment: "enterprise",
    siteName: "Mumbai Corporate Office",
    siteId: "SITE-MUM-ENT-001",
    employeeId: "E123",
    department: "Finance",
    userCategory: "employee",
    password: "387425",
  },
  {
    id: "USER011",
    firstName: "Ravi",
    lastName: "Kumar",
    mobile: "+91-9876543201",
    email: "ravi.kumar@mail.com",
    policyId: "ENT_WIFI_25Mbps_100GB_5Devices_Monthly",
    speed: "Upto 25 Mbps",
    dataVolume: "100 GB",
    deviceLimit: "5",
    dataCycleType: "Monthly",
    devicesCount: 2,
    status: "Active",
    registration: "2024-04-15",
    lastOnline: "1 hour ago",
    usageTotalData: "46.3 GB",
    usageSessions: 55,
    usageAvgSession: "2h 18m",
    usageLastOnline: "1 hour ago",
    location: "Mumbai, Maharashtra",
    segment: "enterprise",
    siteName: "Mumbai Corporate Office",
    siteId: "SITE-MUM-ENT-001",
    employeeId: "E124",
    department: "Operations",
    userCategory: "employee",
    password: "582641",
  },
  {
    id: "USER012",
    firstName: "Neeta",
    lastName: "Singh",
    mobile: "+91-9876543222",
    email: "neeta.singh@mail.com",
    policyId: "ENT_WIFI_50Mbps_200GB_4Devices_Monthly",
    speed: "Upto 50 Mbps",
    dataVolume: "200 GB",
    deviceLimit: "4",
    dataCycleType: "Monthly",
    devicesCount: 2,
    status: "Active",
    registration: "2024-06-15",
    lastOnline: "30 min ago",
    usageTotalData: "82.4 GB",
    usageSessions: 81,
    usageAvgSession: "4h 09m",
    usageLastOnline: "30 min ago",
    location: "Mumbai, Maharashtra",
    segment: "enterprise",
    siteName: "Mumbai Corporate Office",
    siteId: "SITE-MUM-ENT-001",
    employeeId: "E125",
    department: "Sales",
    userCategory: "employee",
    password: "741258",
  },

  // Office - Hyderabad Tech Park (userLevel site with single policy)
  {
    id: "USER023",
    firstName: "Srinivas",
    lastName: "Reddy",
    mobile: "+91-9876123450",
    email: "srinivas.reddy@mail.com",
    policyId: "OFF_WIFI_50Mbps_150GB_3Devices_Monthly",
    speed: "Upto 50 Mbps",
    dataVolume: "150 GB",
    deviceLimit: "3",
    dataCycleType: "Monthly",
    devicesCount: 2,
    status: "Active",
    registration: "2024-02-10",
    lastOnline: "5 min ago",
    usageTotalData: "38.5 GB",
    usageSessions: 62,
    usageAvgSession: "3h 12m",
    usageLastOnline: "5 min ago",
    location: "Hyderabad, Telangana",
    segment: "office",
    siteName: "Hyderabad Tech Park",
    siteId: "SITE-HYD-OFF-007",
    employeeId: "HYD001",
    department: "Engineering",
    userCategory: "employee",
    password: "425781",
  },
  {
    id: "USER024",
    firstName: "Priya",
    lastName: "Venkat",
    mobile: "+91-9876123451",
    email: "priya.venkat@mail.com",
    policyId: "OFF_WIFI_50Mbps_150GB_3Devices_Monthly",
    speed: "Upto 50 Mbps",
    dataVolume: "150 GB",
    deviceLimit: "3",
    dataCycleType: "Monthly",
    devicesCount: 2,
    status: "Active",
    registration: "2024-03-15",
    lastOnline: "15 min ago",
    usageTotalData: "72.3 GB",
    usageSessions: 88,
    usageAvgSession: "4h 05m",
    usageLastOnline: "15 min ago",
    location: "Hyderabad, Telangana",
    segment: "office",
    siteName: "Hyderabad Tech Park",
    siteId: "SITE-HYD-OFF-007",
    employeeId: "HYD002",
    department: "Product",
    userCategory: "employee",
    password: "639184",
  },
  {
    id: "USER025",
    firstName: "Karthik",
    lastName: "Naidu",
    mobile: "+91-9876123452",
    email: "karthik.naidu@mail.com",
    policyId: "OFF_WIFI_50Mbps_150GB_3Devices_Monthly",
    speed: "Upto 50 Mbps",
    dataVolume: "150 GB",
    deviceLimit: "3",
    dataCycleType: "Monthly",
    devicesCount: 2,
    status: "Active",
    registration: "2024-01-20",
    lastOnline: "2 min ago",
    usageTotalData: "156.8 GB",
    usageSessions: 145,
    usageAvgSession: "5h 22m",
    usageLastOnline: "2 min ago",
    location: "Hyderabad, Telangana",
    segment: "office",
    siteName: "Hyderabad Tech Park",
    siteId: "SITE-HYD-OFF-007",
    employeeId: "HYD003",
    department: "Management",
    userCategory: "employee",
    password: "817294",
  },

  // CoLiving - Spectra Urban Living - Bangalore (userLevel site)
  {
    id: "USER003",
    firstName: "Rajesh",
    lastName: "Kumar",
    mobile: "+91-9988776655",
    email: "",
    policyId: "COL_WIFI_10Mbps_50GB_1Devices_Monthly",
    speed: "Upto 10 Mbps",
    dataVolume: "50 GB",
    deviceLimit: "1",
    dataCycleType: "Monthly",
    devicesCount: 1,
    status: "Suspended",
    registration: "2024-02-20",
    lastOnline: "1 hour ago",
    usageTotalData: "8.7 GB",
    usageSessions: 13,
    usageAvgSession: "2h 00m",
    usageLastOnline: "1 hour ago",
    location: "Bangalore, Karnataka",
    segment: "coLiving",
    siteName: "Spectra Urban Living - Bangalore",
    siteId: "SITE-BLR-COL-002",
    residentType: "Tenant",
    roomNumber: "101A",
    userCategory: "resident",
    password: "529834",
  },
  {
    id: "USER013",
    firstName: "Anita",
    lastName: "Shah",
    mobile: "+91-9988776656",
    email: "",
    policyId: "COL_WIFI_20Mbps_100GB_2Devices_Monthly",
    speed: "Upto 20 Mbps",
    dataVolume: "100 GB",
    deviceLimit: "2",
    dataCycleType: "Monthly",
    devicesCount: 2,
    status: "Active",
    registration: "2024-03-20",
    lastOnline: "20 min ago",
    usageTotalData: "49.2 GB",
    usageSessions: 89,
    usageAvgSession: "2h 44m",
    usageLastOnline: "20 min ago",
    location: "Bangalore, Karnataka",
    segment: "coLiving",
    siteName: "Spectra Urban Living - Bangalore",
    siteId: "SITE-BLR-COL-002",
    residentType: "Owner",
    roomNumber: "202B",
    userCategory: "resident",
    password: "346872",
  },
  {
    id: "USER014",
    firstName: "Vipin",
    lastName: "Nair",
    mobile: "+91-9988776657",
    email: "",
    policyId: "COL_WIFI_30Mbps_150GB_3Devices_Monthly",
    speed: "Upto 30 Mbps",
    dataVolume: "150 GB",
    deviceLimit: "3",
    dataCycleType: "Monthly",
    devicesCount: 2,
    status: "Active",
    registration: "2024-04-22",
    lastOnline: "15 min ago",
    usageTotalData: "61.5 GB",
    usageSessions: 72,
    usageAvgSession: "3h 10m",
    usageLastOnline: "15 min ago",
    location: "Bangalore, Karnataka",
    segment: "coLiving",
    siteName: "Spectra Urban Living - Bangalore",
    siteId: "SITE-BLR-COL-002",
    residentType: "Tenant",
    roomNumber: "303C",
    userCategory: "resident",
    password: "192847",
  },
  
  // CoWorking - Spectra WorkHub - Pune (userLevel site, Daily cycle)
  {
    id: "USER005",
    firstName: "Sanjay",
    lastName: "Rao",
    mobile: "+91-9012345678",
    email: "",
    policyId: "COW_WIFI_15Mbps_5GB_1Devices_Daily",
    speed: "Upto 15 Mbps",
    dataVolume: "5 GB",
    deviceLimit: "1",
    dataCycleType: "Daily",
    devicesCount: 1,
    status: "Blocked",
    registration: "2024-03-01",
    lastOnline: "2 days ago",
    usageTotalData: "20.2 GB",
    usageSessions: 15,
    usageAvgSession: "1h 32m",
    usageLastOnline: "2 days ago",
    location: "Pune, Maharashtra",
    segment: "coWorking",
    siteName: "Spectra WorkHub - Pune",
    siteId: "SITE-PUN-COW-003",
    companyName: "Tech Solutions",
    deskNumber: "D12",
    userCategory: "member",
    password: "918352",
  },
  {
    id: "USER015",
    firstName: "Suresh",
    lastName: "Kumar",
    mobile: "+91-9012345679",
    email: "suresh.kumar@mail.com",
    policyId: "COW_WIFI_25Mbps_10GB_2Devices_Daily",
    speed: "Upto 25 Mbps",
    dataVolume: "10 GB",
    deviceLimit: "2",
    dataCycleType: "Daily",
    devicesCount: 1,
    status: "Active",
    registration: "2024-05-01",
    lastOnline: "1 hour ago",
    usageTotalData: "31.6 GB",
    usageSessions: 41,
    usageAvgSession: "2h 05m",
    usageLastOnline: "1 hour ago",
    location: "Pune, Maharashtra",
    segment: "coWorking",
    siteName: "Spectra WorkHub - Pune",
    siteId: "SITE-PUN-COW-003",
    companyName: "StartUp India",
    deskNumber: "A5",
    userCategory: "member",
    password: "658374",
  },
  {
    id: "USER016",
    firstName: "Pooja",
    lastName: "Joshi",
    mobile: "+91-9012345680",
    email: "pooja.joshi@mail.com",
    policyId: "COW_WIFI_50Mbps_20GB_3Devices_Daily",
    speed: "Upto 50 Mbps",
    dataVolume: "20 GB",
    deviceLimit: "3",
    dataCycleType: "Daily",
    devicesCount: 2,
    status: "Active",
    registration: "2024-06-20",
    lastOnline: "30 min ago",
    usageTotalData: "90.8 GB",
    usageSessions: 58,
    usageAvgSession: "4h 15m",
    usageLastOnline: "30 min ago",
    location: "Pune, Maharashtra",
    segment: "coWorking",
    siteName: "Spectra WorkHub - Pune",
    siteId: "SITE-PUN-COW-003",
    companyName: "Freelancers Ltd",
    deskNumber: "C12",
    userCategory: "member",
    password: "487392",
  },
  
  // Hotel - Spectra Grand Hotel - Goa
  {
    id: "USER007",
    firstName: "Vikram",
    lastName: "Chatterjee",
    mobile: "+91-9988123456",
    email: "",
    policyId: "HTL_WIFI_10Mbps_2GB_1Devices_Daily",
    speed: "Upto 10 Mbps",
    dataVolume: "2 GB",
    deviceLimit: "1",
    dataCycleType: "Daily",
    devicesCount: 1,
    status: "Active",
    registration: "2024-03-15",
    lastOnline: "12 min ago",
    usageTotalData: "5.8 GB",
    usageSessions: 7,
    usageAvgSession: "0h 41m",
    usageLastOnline: "12 min ago",
    location: "Goa",
    segment: "hotel",
    siteName: "Spectra Grand Hotel - Goa",
    siteId: "SITE-GOA-HTL-004",
    roomNumber: "305",
    floor: "3",
    checkInDate: "2025-09-01",
    checkOutDate: "2025-09-07",
    userCategory: "guest",
    password: "296153",
  },
  {
    id: "USER017",
    firstName: "Ramesh",
    lastName: "Iyer",
    mobile: "+91-9988123457",
    email: "",
    policyId: "HTL_WIFI_20Mbps_5GB_2Devices_Daily",
    speed: "Upto 20 Mbps",
    dataVolume: "5 GB",
    deviceLimit: "2",
    dataCycleType: "Daily",
    devicesCount: 1,
    status: "Active",
    registration: "2024-04-18",
    lastOnline: "10 min ago",
    usageTotalData: "12.2 GB",
    usageSessions: 18,
    usageAvgSession: "1h 22m",
    usageLastOnline: "10 min ago",
    location: "Goa",
    segment: "hotel",
    siteName: "Spectra Grand Hotel - Goa",
    siteId: "SITE-GOA-HTL-004",
    roomNumber: "312",
    floor: "3",
    checkInDate: "2025-10-01",
    checkOutDate: "2025-10-15",
    userCategory: "guest",
    password: "714589",
  },
  {
    id: "USER018",
    firstName: "Anita",
    lastName: "Kapoor",
    mobile: "+91-9988123458",
    email: "",
    policyId: "HTL_WIFI_50Mbps_Unlimited_3Devices_Daily",
    speed: "Upto 50 Mbps",
    dataVolume: "Unlimited",
    deviceLimit: "3",
    dataCycleType: "Daily",
    devicesCount: 2,
    status: "Suspended",
    registration: "2024-05-25",
    lastOnline: "1 hour ago",
    usageTotalData: "21.9 GB",
    usageSessions: 33,
    usageAvgSession: "1h 47m",
    usageLastOnline: "1 hour ago",
    location: "Goa",
    segment: "hotel",
    siteName: "Spectra Grand Hotel - Goa",
    siteId: "SITE-GOA-HTL-004",
    roomNumber: "320",
    floor: "3",
    checkInDate: "2025-11-05",
    checkOutDate: "2025-11-10",
    userCategory: "guest",
    password: "829163",
  },
  
  // PG - Spectra PG Residency - Chennai (single policy site)
  {
    id: "USER008",
    firstName: "Divya",
    lastName: "Nair",
    mobile: "+91-9876541230",
    email: "",
    policyId: "PG_WIFI_25Mbps_100GB_2Devices_Monthly",
    speed: "Upto 25 Mbps",
    dataVolume: "100 GB",
    deviceLimit: "2",
    dataCycleType: "Monthly",
    devicesCount: 2,
    status: "Suspended",
    registration: "2024-03-12",
    lastOnline: "3 hours ago",
    usageTotalData: "40.4 GB",
    usageSessions: 64,
    usageAvgSession: "2h 41m",
    usageLastOnline: "3 hours ago",
    location: "Chennai, Tamil Nadu",
    segment: "pg",
    siteName: "Spectra PG Residency - Chennai",
    siteId: "SITE-CHN-PGR-005",
    pgType: "Female",
    roomNumber: "B12",
    userCategory: "resident",
    password: "837492",
  },
  {
    id: "USER019",
    firstName: "Sita",
    lastName: "Kumari",
    mobile: "+91-9876541231",
    email: "",
    policyId: "PG_WIFI_25Mbps_100GB_2Devices_Monthly",
    speed: "Upto 25 Mbps",
    dataVolume: "100 GB",
    deviceLimit: "2",
    dataCycleType: "Monthly",
    devicesCount: 1,
    status: "Active",
    registration: "2024-06-20",
    lastOnline: "45 min ago",
    usageTotalData: "24.9 GB",
    usageSessions: 32,
    usageAvgSession: "1h 54m",
    usageLastOnline: "45 min ago",
    location: "Chennai, Tamil Nadu",
    segment: "pg",
    siteName: "Spectra PG Residency - Chennai",
    siteId: "SITE-CHN-PGR-005",
    pgType: "Male",
    roomNumber: "B15",
    userCategory: "resident",
    password: "481726",
  },
  {
    id: "USER020",
    firstName: "Kiran",
    lastName: "Sharma",
    mobile: "+91-9876541232",
    email: "",
    policyId: "PG_WIFI_25Mbps_100GB_2Devices_Monthly",
    speed: "Upto 25 Mbps",
    dataVolume: "100 GB",
    deviceLimit: "2",
    dataCycleType: "Monthly",
    devicesCount: 1,
    status: "Active",
    registration: "2024-06-25",
    lastOnline: "30 min ago",
    usageTotalData: "12.1 GB",
    usageSessions: 24,
    usageAvgSession: "1h 17m",
    usageLastOnline: "30 min ago",
    location: "Chennai, Tamil Nadu",
    segment: "pg",
    siteName: "Spectra PG Residency - Chennai",
    siteId: "SITE-CHN-PGR-005",
    pgType: "Female",
    roomNumber: "B18",
    userCategory: "resident",
    password: "536718",
  },
  
  // Miscellaneous - Spectra Community Hub - Delhi (fixed bandwidth site, max 100 Mbps)
  {
    id: "USER009",
    firstName: "Rahul",
    lastName: "Desai",
    mobile: "+91-9098765432",
    email: "rahul.desai@mail.com",
    policyId: "MIS_WIFI_50Mbps_100GB_5Devices_Monthly",
    speed: "Upto 50 Mbps",
    dataVolume: "100 GB",
    deviceLimit: "5",
    dataCycleType: "Monthly",
    devicesCount: 2,
    status: "Active",
    registration: "2024-03-17",
    lastOnline: "30 sec ago",
    usageTotalData: "77.0 GB",
    usageSessions: 110,
    usageAvgSession: "3h 34m",
    usageLastOnline: "30 sec ago",
    location: "Delhi",
    segment: "miscellaneous",
    siteName: "Spectra Community Hub - Delhi",
    siteId: "SITE-DEL-MIS-006",
    notes: "VIP",
    userCategory: "user",
    password: "194756",
  },
  {
    id: "USER021",
    firstName: "Neelam",
    lastName: "Patel",
    mobile: "+91-9098765433",
    email: "neelam.patel@mail.com",
    policyId: "MIS_WIFI_20Mbps_75GB_3Devices_Monthly",
    speed: "Upto 20 Mbps",
    dataVolume: "75 GB",
    deviceLimit: "3",
    dataCycleType: "Monthly",
    devicesCount: 3,
    status: "Active",
    registration: "2024-04-20",
    lastOnline: "10 min ago",
    usageTotalData: "35.5 GB",
    usageSessions: 60,
    usageAvgSession: "2h 52m",
    usageLastOnline: "10 min ago",
    location: "Delhi",
    segment: "miscellaneous",
    siteName: "Spectra Community Hub - Delhi",
    siteId: "SITE-DEL-MIS-006",
    notes: "Regular",
    userCategory: "user",
    password: "615283",
  },
  {
    id: "USER022",
    firstName: "Raja",
    lastName: "Singh",
    mobile: "+91-9098765434",
    email: "raja.singh@mail.com",
    policyId: "MIS_WIFI_10Mbps_10GB_1Devices_Monthly",
    speed: "Upto 10 Mbps",
    dataVolume: "10 GB",
    deviceLimit: "1",
    dataCycleType: "Monthly",
    devicesCount: 1,
    status: "Suspended",
    registration: "2024-05-20",
    lastOnline: "15 min ago",
    usageTotalData: "2.9 GB",
    usageSessions: 11,
    usageAvgSession: "1h 02m",
    usageLastOnline: "15 min ago",
    location: "Delhi",
    segment: "miscellaneous",
    siteName: "Spectra Community Hub - Delhi",
    siteId: "SITE-DEL-MIS-006",
    notes: "Inactive",
    userCategory: "user",
    password: "789145",
  }
];

// ============================================
// DEVICE DATA - API Format Aligned
// ============================================

/**
 * MissingForAPI (Devices):
 * - Real-time online/offline status from network
 * - Current session bandwidth usage
 * - Device vendor/manufacturer from MAC OUI lookup
 * - Signal strength if connected
 * - AP name if connected
 * 
 * FrontendOnly (Devices):
 * - userId grouping
 * - category (display grouping)
 * - blocked flag (portal-specific)
 */

export const sampleDevices = [
  // Amit Sharma's devices (USER001)
  {
    id: "dev001",
    userId: "USER001",
    name: "iPhone 14 Pro",
    type: "mobile",
    category: "Mobile",
    mac: "00:1B:44:11:3A:B7",
    ip: "192.168.1.142",
    additionDate: "2024-08-15",
    lastUsageDate: "2 hours ago",
    dataUsage: "245 MB",
    online: true,
    blocked: false
  },
  {
    id: "dev002",
    userId: "USER001",
    name: "Lenovo ThinkPad",
    type: "laptop",
    category: "Laptop",
    mac: "00:1B:44:11:3A:D1",
    ip: "192.168.1.159",
    additionDate: "2024-09-01",
    lastUsageDate: "10 minutes ago",
    dataUsage: "1.5 GB",
    online: true,
    blocked: false
  },
  
  // Neeta Singh's devices (USER012)
  {
    id: "dev003",
    userId: "USER012",
    name: "MacBook Air",
    type: "laptop",
    category: "Laptop",
    mac: "00:1B:44:11:3A:C8",
    ip: "192.168.1.156",
    additionDate: "2024-07-22",
    lastUsageDate: "1 hour ago",
    dataUsage: "1.2 GB",
    online: true,
    blocked: false
  },
  {
    id: "dev004",
    userId: "USER012",
    name: "iPhone 12 Mini",
    type: "mobile",
    category: "Mobile",
    mac: "00:1B:44:11:3A:C1",
    ip: "192.168.1.146",
    additionDate: "2024-08-30",
    lastUsageDate: "6 hours ago",
    dataUsage: "234 MB",
    online: false,
    blocked: false
  },
  
  // Rajesh Kumar's devices (USER003)
  {
    id: "dev005",
    userId: "USER003",
    name: "iPhone 13",
    type: "mobile",
    category: "Mobile",
    mac: "00:1B:44:11:3A:B8",
    ip: "192.168.1.143",
    additionDate: "2024-06-10",
    lastUsageDate: "3 hours ago",
    dataUsage: "189 MB",
    online: false,
    blocked: false
  },
  {
    id: "dev006",
    userId: "USER003",
    name: "MacBook Pro 16",
    type: "laptop",
    category: "Laptop",
    mac: "00:1B:44:11:3A:D2",
    ip: "192.168.1.160",
    additionDate: "2024-07-15",
    lastUsageDate: "20 minutes ago",
    dataUsage: "3.2 GB",
    online: true,
    blocked: false
  },
  
  // Vikram Chatterjee's devices (USER007)
  {
    id: "dev007",
    userId: "USER007",
    name: "Dell XPS 15",
    type: "laptop",
    category: "Laptop",
    mac: "00:1B:44:11:3A:C9",
    ip: "192.168.1.157",
    additionDate: "2024-05-18",
    lastUsageDate: "30 minutes ago",
    dataUsage: "890 MB",
    online: true,
    blocked: false
  },
  {
    id: "dev008",
    userId: "USER007",
    name: "Google Pixel 7",
    type: "mobile",
    category: "Mobile",
    mac: "00:1B:44:11:3A:C2",
    ip: "192.168.1.147",
    additionDate: "2024-09-05",
    lastUsageDate: "4 hours ago",
    dataUsage: "345 MB",
    online: false,
    blocked: false
  },
  
  // Divya Nair's devices (USER008)
  {
    id: "dev009",
    userId: "USER008",
    name: "Samsung Galaxy S22",
    type: "mobile",
    category: "Mobile",
    mac: "00:1B:44:11:3A:B9",
    ip: "192.168.1.144",
    additionDate: "2024-06-28",
    lastUsageDate: "5 hours ago",
    dataUsage: "567 MB",
    online: false,
    blocked: false
  },
  {
    id: "dev010",
    userId: "USER008",
    name: "Asus ROG",
    type: "laptop",
    category: "Laptop",
    mac: "00:1B:44:11:3A:D3",
    ip: "192.168.1.161",
    additionDate: "2024-07-10",
    lastUsageDate: "25 minutes ago",
    dataUsage: "2.8 GB",
    online: true,
    blocked: false
  },
  
  // Sanjay Rao's devices (USER005)
  {
    id: "dev011",
    userId: "USER005",
    name: "HP Pavilion",
    type: "laptop",
    category: "Laptop",
    mac: "00:1B:44:11:3A:D0",
    ip: "192.168.1.158",
    additionDate: "2024-08-20",
    lastUsageDate: "15 minutes ago",
    dataUsage: "2.1 GB",
    online: true,
    blocked: true
  },
  {
    id: "dev012",
    userId: "USER005",
    name: "Samsung Galaxy Tab S8",
    type: "mobile",
    category: "Tablet",
    mac: "00:1B:44:11:3A:E5",
    ip: "192.168.1.170",
    additionDate: "2024-09-03",
    lastUsageDate: "2 hours ago",
    dataUsage: "678 MB",
    online: true,
    blocked: false
  },
  
  // Rahul Desai's devices (USER009)
  {
    id: "dev013",
    userId: "USER009",
    name: "iPad Pro",
    type: "mobile",
    category: "Tablet",
    mac: "00:1B:44:11:3A:C0",
    ip: "192.168.1.145",
    additionDate: "2024-09-12",
    lastUsageDate: "45 minutes ago",
    dataUsage: "432 MB",
    online: true,
    blocked: false
  },
  {
    id: "dev014",
    userId: "USER009",
    name: "Microsoft Surface",
    type: "laptop",
    category: "Laptop",
    mac: "00:1B:44:11:3A:D4",
    ip: "192.168.1.162",
    additionDate: "2024-08-05",
    lastUsageDate: "1 hour ago",
    dataUsage: "1.8 GB",
    online: true,
    blocked: false
  },
  
  // Ravi Kumar's devices (USER011)
  {
    id: "dev015",
    userId: "USER011",
    name: "OnePlus 11",
    type: "mobile",
    category: "Mobile",
    mac: "00:1B:44:11:3A:C3",
    ip: "192.168.1.148",
    additionDate: "2024-07-18",
    lastUsageDate: "3 hours ago",
    dataUsage: "456 MB",
    online: false,
    blocked: false
  },
  {
    id: "dev016",
    userId: "USER011",
    name: "Acer Aspire",
    type: "laptop",
    category: "Laptop",
    mac: "00:1B:44:11:3A:D5",
    ip: "192.168.1.163",
    additionDate: "2024-06-22",
    lastUsageDate: "50 minutes ago",
    dataUsage: "2.3 GB",
    online: true,
    blocked: false
  },
  
  // Anita Shah's devices (USER013)
  {
    id: "dev017",
    userId: "USER013",
    name: "Xiaomi 13 Pro",
    type: "mobile",
    category: "Mobile",
    mac: "00:1B:44:11:3A:C4",
    ip: "192.168.1.149",
    additionDate: "2024-08-08",
    lastUsageDate: "4 hours ago",
    dataUsage: "389 MB",
    online: false,
    blocked: false
  },
  {
    id: "dev018",
    userId: "USER013",
    name: "HP Envy",
    type: "laptop",
    category: "Laptop",
    mac: "00:1B:44:11:3A:D6",
    ip: "192.168.1.164",
    additionDate: "2024-07-25",
    lastUsageDate: "35 minutes ago",
    dataUsage: "1.9 GB",
    online: true,
    blocked: false
  },
  
  // Vipin Nair's devices (USER014)
  {
    id: "dev019",
    userId: "USER014",
    name: "Vivo X90",
    type: "mobile",
    category: "Mobile",
    mac: "00:1B:44:11:3A:C5",
    ip: "192.168.1.150",
    additionDate: "2024-09-01",
    lastUsageDate: "1 hour ago",
    dataUsage: "523 MB",
    online: true,
    blocked: false
  },
  {
    id: "dev020",
    userId: "USER014",
    name: "Lenovo IdeaPad",
    type: "laptop",
    category: "Laptop",
    mac: "00:1B:44:11:3A:D7",
    ip: "192.168.1.165",
    additionDate: "2024-06-30",
    lastUsageDate: "22 minutes ago",
    dataUsage: "2.6 GB",
    online: true,
    blocked: false
  },
  
  // Suresh Kumar's devices (USER015)
  {
    id: "dev021",
    userId: "USER015",
    name: "Realme GT 2",
    type: "mobile",
    category: "Mobile",
    mac: "00:1B:44:11:3A:C6",
    ip: "192.168.1.151",
    additionDate: "2024-07-12",
    lastUsageDate: "5 hours ago",
    dataUsage: "412 MB",
    online: false,
    blocked: false
  },
  
  // Pooja Joshi's devices (USER016)
  {
    id: "dev022",
    userId: "USER016",
    name: "Oppo Find X5",
    type: "mobile",
    category: "Mobile",
    mac: "00:1B:44:11:3A:C7",
    ip: "192.168.1.152",
    additionDate: "2024-08-25",
    lastUsageDate: "2 hours ago",
    dataUsage: "345 MB",
    online: true,
    blocked: false
  },
  {
    id: "dev023",
    userId: "USER016",
    name: "Dell Inspiron",
    type: "laptop",
    category: "Laptop",
    mac: "00:1B:44:11:3A:D8",
    ip: "192.168.1.166",
    additionDate: "2024-07-05",
    lastUsageDate: "40 minutes ago",
    dataUsage: "1.7 GB",
    online: true,
    blocked: false
  },
  
  // Ramesh Iyer's device (USER017)
  {
    id: "dev024",
    userId: "USER017",
    name: "Asus ZenBook",
    type: "laptop",
    category: "Laptop",
    mac: "00:1B:44:11:3A:D9",
    ip: "192.168.1.167",
    additionDate: "2024-06-15",
    lastUsageDate: "3 days ago",
    dataUsage: "850 MB",
    online: false,
    blocked: false
  },
  
  // Anita Kapoor's devices (USER018)
  {
    id: "dev025",
    userId: "USER018",
    name: "Nothing Phone 2",
    type: "mobile",
    category: "Mobile",
    mac: "00:1B:44:11:3A:CA",
    ip: "192.168.1.153",
    additionDate: "2024-09-10",
    lastUsageDate: "30 minutes ago",
    dataUsage: "298 MB",
    online: true,
    blocked: false
  },
  {
    id: "dev026",
    userId: "USER018",
    name: "MSI Prestige",
    type: "laptop",
    category: "Laptop",
    mac: "00:1B:44:11:3A:DA",
    ip: "192.168.1.168",
    additionDate: "2024-08-12",
    lastUsageDate: "18 minutes ago",
    dataUsage: "3.1 GB",
    online: true,
    blocked: false
  },
  
  // Sita Kumari's device (USER019)
  {
    id: "dev027",
    userId: "USER019",
    name: "Motorola Edge 40",
    type: "mobile",
    category: "Mobile",
    mac: "00:1B:44:11:3A:CB",
    ip: "192.168.1.154",
    additionDate: "2024-07-28",
    lastUsageDate: "6 hours ago",
    dataUsage: "478 MB",
    online: false,
    blocked: false
  },

  // Kiran Sharma's device (USER020)
  {
    id: "dev028",
    userId: "USER020",
    name: "Samsung Galaxy A54",
    type: "mobile",
    category: "Mobile",
    mac: "00:1B:44:11:3A:CC",
    ip: "192.168.1.155",
    additionDate: "2024-08-02",
    lastUsageDate: "2 hours ago",
    dataUsage: "312 MB",
    online: true,
    blocked: false
  },

  // Neelam Patel's devices (USER021)
  {
    id: "dev029",
    userId: "USER021",
    name: "Redmi Note 12",
    type: "mobile",
    category: "Mobile",
    mac: "00:1B:44:11:3A:CD",
    ip: "192.168.1.171",
    additionDate: "2024-07-08",
    lastUsageDate: "45 minutes ago",
    dataUsage: "289 MB",
    online: true,
    blocked: false
  },
  {
    id: "dev030",
    userId: "USER021",
    name: "HP Pavilion 15",
    type: "laptop",
    category: "Laptop",
    mac: "00:1B:44:11:3A:DB",
    ip: "192.168.1.172",
    additionDate: "2024-06-18",
    lastUsageDate: "1 hour ago",
    dataUsage: "1.4 GB",
    online: true,
    blocked: false
  },
  {
    id: "dev031",
    userId: "USER021",
    name: "iPad Mini",
    type: "mobile",
    category: "Tablet",
    mac: "00:1B:44:11:3A:CE",
    ip: "192.168.1.173",
    additionDate: "2024-08-15",
    lastUsageDate: "3 hours ago",
    dataUsage: "567 MB",
    online: false,
    blocked: false
  },

  // Raja Singh's device (USER022)
  {
    id: "dev032",
    userId: "USER022",
    name: "Poco X5",
    type: "mobile",
    category: "Mobile",
    mac: "00:1B:44:11:3A:CF",
    ip: "192.168.1.174",
    additionDate: "2024-09-01",
    lastUsageDate: "4 hours ago",
    dataUsage: "156 MB",
    online: false,
    blocked: false
  },

  // Srinivas Reddy's devices (USER023 - Office)
  {
    id: "dev033",
    userId: "USER023",
    name: "Dell Latitude 5520",
    type: "laptop",
    category: "Laptop",
    mac: "00:1B:44:11:3A:E0",
    ip: "192.168.2.101",
    additionDate: "2024-02-15",
    lastUsageDate: "8 minutes ago",
    dataUsage: "2.4 GB",
    online: true,
    blocked: false
  },
  {
    id: "dev034",
    userId: "USER023",
    name: "OnePlus 12",
    type: "mobile",
    category: "Mobile",
    mac: "00:1B:44:11:3A:E1",
    ip: "192.168.2.102",
    additionDate: "2024-03-01",
    lastUsageDate: "25 minutes ago",
    dataUsage: "456 MB",
    online: true,
    blocked: false
  },

  // Priya Venkat's devices (USER024 - Office)
  {
    id: "dev035",
    userId: "USER024",
    name: "MacBook Pro 14",
    type: "laptop",
    category: "Laptop",
    mac: "00:1B:44:11:3A:E2",
    ip: "192.168.2.103",
    additionDate: "2024-03-20",
    lastUsageDate: "12 minutes ago",
    dataUsage: "3.8 GB",
    online: true,
    blocked: false
  },
  {
    id: "dev036",
    userId: "USER024",
    name: "iPhone 15 Pro",
    type: "mobile",
    category: "Mobile",
    mac: "00:1B:44:11:3A:E3",
    ip: "192.168.2.104",
    additionDate: "2024-04-05",
    lastUsageDate: "1 hour ago",
    dataUsage: "612 MB",
    online: false,
    blocked: false
  },

  // Karthik Naidu's devices (USER025 - Office)
  {
    id: "dev037",
    userId: "USER025",
    name: "ThinkPad X1 Carbon",
    type: "laptop",
    category: "Laptop",
    mac: "00:1B:44:11:3A:E4",
    ip: "192.168.2.105",
    additionDate: "2024-01-25",
    lastUsageDate: "3 minutes ago",
    dataUsage: "5.2 GB",
    online: true,
    blocked: false
  },
  {
    id: "dev038",
    userId: "USER025",
    name: "Samsung Galaxy S24 Ultra",
    type: "mobile",
    category: "Mobile",
    mac: "00:1B:44:11:3A:E6",
    ip: "192.168.2.106",
    additionDate: "2024-02-10",
    lastUsageDate: "18 minutes ago",
    dataUsage: "892 MB",
    online: true,
    blocked: false
  },
  {
    id: "dev039",
    userId: "USER025",
    name: "iPad Pro 12.9",
    type: "mobile",
    category: "Tablet",
    mac: "00:1B:44:11:3A:E7",
    ip: "192.168.2.107",
    additionDate: "2024-03-15",
    lastUsageDate: "2 hours ago",
    dataUsage: "1.1 GB",
    online: false,
    blocked: false
  },

  // ============================================
  // DIGITAL/SMART DEVICES - TVs, CCTV, DVRs, Biometric, etc. (1 device per license)
  // Each digital device has an auto-generated deviceUserId
  // subtype field matches filter values from segmentDeviceConfig.js
  // ============================================

  // =====================
  // PG Digital Devices
  // =====================
  {
    id: "dev040",
    deviceUserId: "TV_PG_001",
    deviceUserName: "Common Area TV",
    name: "Samsung Smart TV 55\"",
    type: "digital",
    subtype: "smart_tv",
    category: "Smart TV",
    mac: "00:1B:44:22:AA:01",
    ip: "192.168.5.101",
    additionDate: "2024-01-10",
    lastUsageDate: "5 min ago",
    dataUsage: "8.5 GB",
    online: true,
    blocked: false,
    segment: "pg",
    siteId: "SITE-CHN-PGR-005",
    policyId: "PG_DEVICE_10Mbps_Unlimited_1Device_Monthly",
    location: "Ground Floor Common Room",
    registeredBy: "admin@pg-residency.com"
  },
  {
    id: "dev043",
    deviceUserId: "CCTV_PG_001",
    deviceUserName: "Main Gate CCTV",
    name: "Hikvision CCTV Camera",
    type: "digital",
    subtype: "cctv",
    category: "CCTV",
    mac: "00:1B:44:22:AA:02",
    ip: "192.168.5.102",
    additionDate: "2024-01-15",
    lastUsageDate: "1 min ago",
    dataUsage: "32.4 GB",
    online: true,
    blocked: false,
    segment: "pg",
    siteId: "SITE-CHN-PGR-005",
    policyId: "PG_DEVICE_10Mbps_Unlimited_1Device_Monthly",
    location: "Main Gate",
    registeredBy: "admin@pg-residency.com"
  },
  {
    id: "dev061",
    deviceUserId: "DVR_PG_001",
    deviceUserName: "Security DVR",
    name: "CP Plus 8CH DVR",
    type: "digital",
    subtype: "dvr",
    category: "DVR",
    mac: "00:1B:44:22:AA:03",
    ip: "192.168.5.103",
    additionDate: "2024-01-20",
    lastUsageDate: "2 sec ago",
    dataUsage: "45.8 GB",
    online: true,
    blocked: false,
    segment: "pg",
    siteId: "SITE-CHN-PGR-005",
    policyId: "PG_DEVICE_10Mbps_Unlimited_1Device_Monthly",
    location: "Security Room",
    registeredBy: "admin@pg-residency.com"
  },
  {
    id: "dev062",
    deviceUserId: "BIO_PG_001",
    deviceUserName: "Entry Biometric",
    name: "eSSL X990 Biometric",
    type: "digital",
    subtype: "biometric",
    category: "Biometric",
    mac: "00:1B:44:22:AA:04",
    ip: "192.168.5.104",
    additionDate: "2024-02-01",
    lastUsageDate: "30 sec ago",
    dataUsage: "85 MB",
    online: true,
    blocked: false,
    segment: "pg",
    siteId: "SITE-CHN-PGR-005",
    policyId: "PG_DEVICE_10Mbps_Unlimited_1Device_Monthly",
    location: "Main Entrance",
    registeredBy: "admin@pg-residency.com"
  },
  {
    id: "dev063",
    deviceUserId: "ACC_PG_001",
    deviceUserName: "Gate Access Control",
    name: "HID ProxPoint Plus Reader",
    type: "digital",
    subtype: "access_control",
    category: "Access Control",
    mac: "00:1B:44:22:AA:05",
    ip: "192.168.5.105",
    additionDate: "2024-02-10",
    lastUsageDate: "15 sec ago",
    dataUsage: "45 MB",
    online: true,
    blocked: false,
    segment: "pg",
    siteId: "SITE-CHN-PGR-005",
    policyId: "PG_DEVICE_10Mbps_Unlimited_1Device_Monthly",
    location: "Main Gate",
    registeredBy: "admin@pg-residency.com"
  },
  {
    id: "dev064",
    deviceUserId: "INT_PG_001",
    deviceUserName: "Reception Intercom",
    name: "Panasonic KX-NT553",
    type: "digital",
    subtype: "intercom",
    category: "Intercom",
    mac: "00:1B:44:22:AA:06",
    ip: "192.168.5.106",
    additionDate: "2024-02-15",
    lastUsageDate: "10 min ago",
    dataUsage: "25 MB",
    online: true,
    blocked: false,
    segment: "pg",
    siteId: "SITE-CHN-PGR-005",
    policyId: "PG_DEVICE_10Mbps_Unlimited_1Device_Monthly",
    location: "Reception Desk",
    registeredBy: "admin@pg-residency.com"
  },

  // =====================
  // Co-Living Digital Devices
  // =====================
  {
    id: "dev041",
    deviceUserId: "DVR_COL_001",
    deviceUserName: "Security DVR System",
    name: "Dahua 16CH DVR",
    type: "digital",
    subtype: "dvr",
    category: "DVR",
    mac: "00:1B:44:22:BB:01",
    ip: "192.168.3.201",
    additionDate: "2024-02-15",
    lastUsageDate: "1 min ago",
    dataUsage: "45.2 GB",
    online: true,
    blocked: false,
    segment: "coLiving",
    siteId: "SITE-BLR-COL-002",
    policyId: "COL_DEVICE_10Mbps_Unlimited_1Device_Monthly",
    location: "Security Room - Building A",
    registeredBy: "security@urban-living.com"
  },
  {
    id: "dev044",
    deviceUserId: "BIO_COL_001",
    deviceUserName: "Entry Biometric",
    name: "eSSL X990 Biometric",
    type: "digital",
    subtype: "biometric",
    category: "Biometric",
    mac: "00:1B:44:22:BB:02",
    ip: "192.168.3.202",
    additionDate: "2024-02-20",
    lastUsageDate: "30 sec ago",
    dataUsage: "125 MB",
    online: true,
    blocked: false,
    segment: "coLiving",
    siteId: "SITE-BLR-COL-002",
    policyId: "COL_DEVICE_10Mbps_Unlimited_1Device_Monthly",
    location: "Main Entrance - Building A",
    registeredBy: "admin@urban-living.com"
  },
  {
    id: "dev045",
    deviceUserId: "TV_COL_001",
    deviceUserName: "Lounge TV",
    name: "LG OLED 65\" TV",
    type: "digital",
    subtype: "smart_tv",
    category: "Smart TV",
    mac: "00:1B:44:22:BB:03",
    ip: "192.168.3.203",
    additionDate: "2024-03-01",
    lastUsageDate: "2 hours ago",
    dataUsage: "15.8 GB",
    online: false,
    blocked: false,
    segment: "coLiving",
    siteId: "SITE-BLR-COL-002",
    policyId: "COL_DEVICE_10Mbps_Unlimited_1Device_Monthly",
    location: "Common Lounge",
    registeredBy: "admin@urban-living.com"
  },
  {
    id: "dev065",
    deviceUserId: "CCTV_COL_001",
    deviceUserName: "Parking Camera",
    name: "Hikvision DS-2CD2143G2-I",
    type: "digital",
    subtype: "cctv",
    category: "CCTV",
    mac: "00:1B:44:22:BB:04",
    ip: "192.168.3.204",
    additionDate: "2024-03-05",
    lastUsageDate: "5 sec ago",
    dataUsage: "38.5 GB",
    online: true,
    blocked: false,
    segment: "coLiving",
    siteId: "SITE-BLR-COL-002",
    policyId: "COL_DEVICE_10Mbps_Unlimited_1Device_Monthly",
    location: "Parking Area",
    registeredBy: "security@urban-living.com"
  },
  {
    id: "dev066",
    deviceUserId: "SEN_COL_001",
    deviceUserName: "Fire Sensor Hub",
    name: "Honeywell Fire Sensor System",
    type: "digital",
    subtype: "sensor",
    category: "Sensor",
    mac: "00:1B:44:22:BB:05",
    ip: "192.168.3.205",
    additionDate: "2024-03-10",
    lastUsageDate: "1 min ago",
    dataUsage: "65 MB",
    online: true,
    blocked: false,
    segment: "coLiving",
    siteId: "SITE-BLR-COL-002",
    policyId: "COL_DEVICE_10Mbps_Unlimited_1Device_Monthly",
    location: "Building A - All Floors",
    registeredBy: "facilities@urban-living.com"
  },
  {
    id: "dev067",
    deviceUserId: "ACC_COL_001",
    deviceUserName: "Building Access Control",
    name: "HID iCLASS SE R40",
    type: "digital",
    subtype: "access_control",
    category: "Access Control",
    mac: "00:1B:44:22:BB:06",
    ip: "192.168.3.206",
    additionDate: "2024-03-15",
    lastUsageDate: "20 sec ago",
    dataUsage: "95 MB",
    online: true,
    blocked: false,
    segment: "coLiving",
    siteId: "SITE-BLR-COL-002",
    policyId: "COL_DEVICE_10Mbps_Unlimited_1Device_Monthly",
    location: "Main Gate - Building A",
    registeredBy: "admin@urban-living.com"
  },
  {
    id: "dev068",
    deviceUserId: "INT_COL_001",
    deviceUserName: "Lobby Intercom",
    name: "Grandstream GXV3350",
    type: "digital",
    subtype: "intercom",
    category: "Intercom",
    mac: "00:1B:44:22:BB:07",
    ip: "192.168.3.207",
    additionDate: "2024-03-20",
    lastUsageDate: "5 min ago",
    dataUsage: "45 MB",
    online: true,
    blocked: false,
    segment: "coLiving",
    siteId: "SITE-BLR-COL-002",
    policyId: "COL_DEVICE_10Mbps_Unlimited_1Device_Monthly",
    location: "Lobby - Building A",
    registeredBy: "admin@urban-living.com"
  },

  // =====================
  // Hotel Digital Devices
  // =====================
  {
    id: "dev042",
    deviceUserId: "TV_HTL_001",
    deviceUserName: "Lobby Display",
    name: "Sony Bravia 75\" Display",
    type: "digital",
    subtype: "smart_tv",
    category: "Smart TV",
    mac: "00:1B:44:22:CC:01",
    ip: "192.168.4.151",
    additionDate: "2024-03-01",
    lastUsageDate: "3 min ago",
    dataUsage: "12.8 GB",
    online: true,
    blocked: false,
    segment: "hotel",
    siteId: "SITE-GOA-HTL-004",
    policyId: "HTL_DEVICE_10Mbps_Unlimited_1Device_Daily",
    location: "Main Lobby",
    registeredBy: "it@grandhotel-goa.com"
  },
  {
    id: "dev046",
    deviceUserId: "CCTV_HTL_001",
    deviceUserName: "Pool Area Camera",
    name: "CP Plus Dome Camera",
    type: "digital",
    subtype: "cctv",
    category: "CCTV",
    mac: "00:1B:44:22:CC:02",
    ip: "192.168.4.152",
    additionDate: "2024-03-05",
    lastUsageDate: "10 sec ago",
    dataUsage: "28.5 GB",
    online: true,
    blocked: false,
    segment: "hotel",
    siteId: "SITE-GOA-HTL-004",
    policyId: "HTL_DEVICE_10Mbps_Unlimited_1Device_Daily",
    location: "Swimming Pool Area",
    registeredBy: "security@grandhotel-goa.com"
  },
  {
    id: "dev047",
    deviceUserId: "DVR_HTL_001",
    deviceUserName: "Security DVR",
    name: "Hikvision 32CH NVR",
    type: "digital",
    subtype: "dvr",
    category: "DVR",
    mac: "00:1B:44:22:CC:03",
    ip: "192.168.4.153",
    additionDate: "2024-03-10",
    lastUsageDate: "5 sec ago",
    dataUsage: "156.2 GB",
    online: true,
    blocked: false,
    segment: "hotel",
    siteId: "SITE-GOA-HTL-004",
    policyId: "HTL_DEVICE_10Mbps_Unlimited_1Device_Daily",
    location: "Security Control Room",
    registeredBy: "security@grandhotel-goa.com"
  },
  {
    id: "dev069",
    deviceUserId: "BIO_HTL_001",
    deviceUserName: "Staff Entry Biometric",
    name: "ZKTeco MultiBio 700",
    type: "digital",
    subtype: "biometric",
    category: "Biometric",
    mac: "00:1B:44:22:CC:04",
    ip: "192.168.4.154",
    additionDate: "2024-03-15",
    lastUsageDate: "2 min ago",
    dataUsage: "125 MB",
    online: true,
    blocked: false,
    segment: "hotel",
    siteId: "SITE-GOA-HTL-004",
    policyId: "HTL_DEVICE_10Mbps_Unlimited_1Device_Daily",
    location: "Staff Entrance",
    registeredBy: "hr@grandhotel-goa.com"
  },
  {
    id: "dev070",
    deviceUserId: "ACC_HTL_001",
    deviceUserName: "Room Access System",
    name: "ASSA ABLOY VingCard",
    type: "digital",
    subtype: "access_control",
    category: "Access Control",
    mac: "00:1B:44:22:CC:05",
    ip: "192.168.4.155",
    additionDate: "2024-03-20",
    lastUsageDate: "1 min ago",
    dataUsage: "85 MB",
    online: true,
    blocked: false,
    segment: "hotel",
    siteId: "SITE-GOA-HTL-004",
    policyId: "HTL_DEVICE_10Mbps_Unlimited_1Device_Daily",
    location: "All Guest Rooms",
    registeredBy: "it@grandhotel-goa.com"
  },
  {
    id: "dev071",
    deviceUserId: "INT_HTL_001",
    deviceUserName: "Reception Intercom",
    name: "Grandstream GXV3380",
    type: "digital",
    subtype: "intercom",
    category: "Intercom",
    mac: "00:1B:44:22:CC:06",
    ip: "192.168.4.156",
    additionDate: "2024-03-25",
    lastUsageDate: "8 min ago",
    dataUsage: "65 MB",
    online: true,
    blocked: false,
    segment: "hotel",
    siteId: "SITE-GOA-HTL-004",
    policyId: "HTL_DEVICE_10Mbps_Unlimited_1Device_Daily",
    location: "Reception Counter",
    registeredBy: "it@grandhotel-goa.com"
  },
  {
    id: "dev072",
    deviceUserId: "POS_HTL_001",
    deviceUserName: "Restaurant POS",
    name: "Square Terminal",
    type: "digital",
    subtype: "pos",
    category: "POS Terminal",
    mac: "00:1B:44:22:CC:07",
    ip: "192.168.4.157",
    additionDate: "2024-04-01",
    lastUsageDate: "15 min ago",
    dataUsage: "245 MB",
    online: true,
    blocked: false,
    segment: "hotel",
    siteId: "SITE-GOA-HTL-004",
    policyId: "HTL_DEVICE_10Mbps_Unlimited_1Device_Daily",
    location: "Main Restaurant",
    registeredBy: "finance@grandhotel-goa.com"
  },
  {
    id: "dev073",
    deviceUserId: "DIS_HTL_001",
    deviceUserName: "Welcome Display",
    name: "LG 55\" Digital Signage",
    type: "digital",
    subtype: "display",
    category: "Digital Display",
    mac: "00:1B:44:22:CC:08",
    ip: "192.168.4.158",
    additionDate: "2024-04-05",
    lastUsageDate: "1 min ago",
    dataUsage: "4.5 GB",
    online: true,
    blocked: false,
    segment: "hotel",
    siteId: "SITE-GOA-HTL-004",
    policyId: "HTL_DEVICE_10Mbps_Unlimited_1Device_Daily",
    location: "Entrance Lobby",
    registeredBy: "marketing@grandhotel-goa.com"
  },
  {
    id: "dev074",
    deviceUserId: "KIO_HTL_001",
    deviceUserName: "Self Check-in Kiosk",
    name: "KIOSK Information Systems",
    type: "digital",
    subtype: "kiosk",
    category: "Kiosk",
    mac: "00:1B:44:22:CC:09",
    ip: "192.168.4.159",
    additionDate: "2024-04-10",
    lastUsageDate: "25 min ago",
    dataUsage: "1.2 GB",
    online: true,
    blocked: false,
    segment: "hotel",
    siteId: "SITE-GOA-HTL-004",
    policyId: "HTL_DEVICE_10Mbps_Unlimited_1Device_Daily",
    location: "Main Lobby",
    registeredBy: "it@grandhotel-goa.com"
  },

  // =====================
  // Enterprise Digital Devices (Mumbai Corporate Office)
  // =====================
  {
    id: "dev048",
    deviceUserId: "CCTV_ENT_001",
    deviceUserName: "Main Lobby CCTV",
    name: "Axis P3245-V Network Camera",
    type: "digital",
    subtype: "cctv",
    category: "CCTV",
    mac: "00:1B:44:33:AA:01",
    ip: "192.168.1.201",
    additionDate: "2024-01-20",
    lastUsageDate: "2 sec ago",
    dataUsage: "85.4 GB",
    online: true,
    blocked: false,
    segment: "enterprise",
    siteId: "SITE-MUM-ENT-001",
    policyId: "ENT_DEVICE_50Mbps_Unlimited_1Device_Monthly",
    location: "Main Lobby - Ground Floor",
    registeredBy: "it-admin@corporate.com"
  },
  {
    id: "dev049",
    deviceUserId: "DVR_ENT_001",
    deviceUserName: "Central NVR System",
    name: "Milestone XProtect NVR",
    type: "digital",
    subtype: "dvr",
    category: "DVR",
    mac: "00:1B:44:33:AA:02",
    ip: "192.168.1.202",
    additionDate: "2024-01-20",
    lastUsageDate: "1 sec ago",
    dataUsage: "456.8 GB",
    online: true,
    blocked: false,
    segment: "enterprise",
    siteId: "SITE-MUM-ENT-001",
    policyId: "ENT_DEVICE_100Mbps_Unlimited_1Device_Monthly",
    location: "Server Room - 2nd Floor",
    registeredBy: "it-admin@corporate.com"
  },
  {
    id: "dev050",
    deviceUserId: "BIO_ENT_001",
    deviceUserName: "Main Entry Biometric",
    name: "Suprema BioStation 2",
    type: "digital",
    subtype: "biometric",
    category: "Biometric",
    mac: "00:1B:44:33:AA:03",
    ip: "192.168.1.203",
    additionDate: "2024-02-01",
    lastUsageDate: "15 sec ago",
    dataUsage: "245 MB",
    online: true,
    blocked: false,
    segment: "enterprise",
    siteId: "SITE-MUM-ENT-001",
    policyId: "ENT_DEVICE_50Mbps_Unlimited_1Device_Monthly",
    location: "Main Entrance Gate",
    registeredBy: "hr-admin@corporate.com"
  },
  {
    id: "dev051",
    deviceUserId: "TV_ENT_001",
    deviceUserName: "Conference Room Display",
    name: "Samsung QLED 85\" Display",
    type: "digital",
    subtype: "smart_tv",
    category: "Smart TV",
    mac: "00:1B:44:33:AA:04",
    ip: "192.168.1.204",
    additionDate: "2024-02-15",
    lastUsageDate: "30 min ago",
    dataUsage: "12.5 GB",
    online: false,
    blocked: false,
    segment: "enterprise",
    siteId: "SITE-MUM-ENT-001",
    policyId: "ENT_DEVICE_50Mbps_Unlimited_1Device_Monthly",
    location: "Board Room - 5th Floor",
    registeredBy: "facilities@corporate.com"
  },
  {
    id: "dev052",
    deviceUserId: "PRN_ENT_001",
    deviceUserName: "Network Printer Floor 3",
    name: "HP LaserJet Enterprise M609",
    type: "digital",
    subtype: "printer",
    category: "Printer",
    mac: "00:1B:44:33:AA:05",
    ip: "192.168.1.205",
    additionDate: "2024-03-01",
    lastUsageDate: "5 min ago",
    dataUsage: "1.8 GB",
    online: true,
    blocked: false,
    segment: "enterprise",
    siteId: "SITE-MUM-ENT-001",
    policyId: "ENT_DEVICE_50Mbps_Unlimited_1Device_Monthly",
    location: "Printing Station - 3rd Floor",
    registeredBy: "it-admin@corporate.com"
  },
  {
    id: "dev075",
    deviceUserId: "SEN_ENT_001",
    deviceUserName: "Environmental Sensor Hub",
    name: "Honeywell Building Sensor",
    type: "digital",
    subtype: "sensor",
    category: "Sensor",
    mac: "00:1B:44:33:AA:06",
    ip: "192.168.1.206",
    additionDate: "2024-03-05",
    lastUsageDate: "30 sec ago",
    dataUsage: "125 MB",
    online: true,
    blocked: false,
    segment: "enterprise",
    siteId: "SITE-MUM-ENT-001",
    policyId: "ENT_DEVICE_50Mbps_Unlimited_1Device_Monthly",
    location: "Server Room - 2nd Floor",
    registeredBy: "facilities@corporate.com"
  },
  {
    id: "dev076",
    deviceUserId: "IOT_ENT_001",
    deviceUserName: "Smart Lighting Controller",
    name: "Philips Dynalite Controller",
    type: "digital",
    subtype: "iot",
    category: "IoT Device",
    mac: "00:1B:44:33:AA:07",
    ip: "192.168.1.207",
    additionDate: "2024-03-10",
    lastUsageDate: "1 min ago",
    dataUsage: "85 MB",
    online: true,
    blocked: false,
    segment: "enterprise",
    siteId: "SITE-MUM-ENT-001",
    policyId: "ENT_DEVICE_50Mbps_Unlimited_1Device_Monthly",
    location: "Building Management System",
    registeredBy: "facilities@corporate.com"
  },
  {
    id: "dev077",
    deviceUserId: "ACC_ENT_001",
    deviceUserName: "Server Room Access",
    name: "HID Global Reader",
    type: "digital",
    subtype: "access_control",
    category: "Access Control",
    mac: "00:1B:44:33:AA:08",
    ip: "192.168.1.208",
    additionDate: "2024-03-15",
    lastUsageDate: "45 sec ago",
    dataUsage: "65 MB",
    online: true,
    blocked: false,
    segment: "enterprise",
    siteId: "SITE-MUM-ENT-001",
    policyId: "ENT_DEVICE_50Mbps_Unlimited_1Device_Monthly",
    location: "Server Room Door",
    registeredBy: "it-admin@corporate.com"
  },
  {
    id: "dev078",
    deviceUserId: "INT_ENT_001",
    deviceUserName: "Reception Intercom",
    name: "Cisco IP Phone 8845",
    type: "digital",
    subtype: "intercom",
    category: "Intercom",
    mac: "00:1B:44:33:AA:09",
    ip: "192.168.1.209",
    additionDate: "2024-03-20",
    lastUsageDate: "12 min ago",
    dataUsage: "145 MB",
    online: true,
    blocked: false,
    segment: "enterprise",
    siteId: "SITE-MUM-ENT-001",
    policyId: "ENT_DEVICE_50Mbps_Unlimited_1Device_Monthly",
    location: "Main Reception",
    registeredBy: "it-admin@corporate.com"
  },
  {
    id: "dev079",
    deviceUserId: "POS_ENT_001",
    deviceUserName: "Cafeteria POS",
    name: "Clover Station Duo",
    type: "digital",
    subtype: "pos",
    category: "POS Terminal",
    mac: "00:1B:44:33:AA:10",
    ip: "192.168.1.210",
    additionDate: "2024-03-25",
    lastUsageDate: "8 min ago",
    dataUsage: "325 MB",
    online: true,
    blocked: false,
    segment: "enterprise",
    siteId: "SITE-MUM-ENT-001",
    policyId: "ENT_DEVICE_50Mbps_Unlimited_1Device_Monthly",
    location: "Cafeteria - Ground Floor",
    registeredBy: "finance@corporate.com"
  },
  {
    id: "dev080",
    deviceUserId: "DIS_ENT_001",
    deviceUserName: "Lobby Info Display",
    name: "Samsung QB75R Digital Signage",
    type: "digital",
    subtype: "display",
    category: "Digital Display",
    mac: "00:1B:44:33:AA:11",
    ip: "192.168.1.211",
    additionDate: "2024-04-01",
    lastUsageDate: "2 min ago",
    dataUsage: "5.2 GB",
    online: true,
    blocked: false,
    segment: "enterprise",
    siteId: "SITE-MUM-ENT-001",
    policyId: "ENT_DEVICE_50Mbps_Unlimited_1Device_Monthly",
    location: "Main Lobby",
    registeredBy: "marketing@corporate.com"
  },
  {
    id: "dev081",
    deviceUserId: "KIO_ENT_001",
    deviceUserName: "Visitor Kiosk",
    name: "KIOSK Visitor Management",
    type: "digital",
    subtype: "kiosk",
    category: "Kiosk",
    mac: "00:1B:44:33:AA:12",
    ip: "192.168.1.212",
    additionDate: "2024-04-05",
    lastUsageDate: "18 min ago",
    dataUsage: "985 MB",
    online: true,
    blocked: false,
    segment: "enterprise",
    siteId: "SITE-MUM-ENT-001",
    policyId: "ENT_DEVICE_50Mbps_Unlimited_1Device_Monthly",
    location: "Reception Area",
    registeredBy: "facilities@corporate.com"
  },

  // =====================
  // Office Digital Devices (Hyderabad Tech Park)
  // =====================
  {
    id: "dev053",
    deviceUserId: "CCTV_OFF_001",
    deviceUserName: "Parking Area Camera",
    name: "Dahua IPC-HFW2831S-S",
    type: "digital",
    subtype: "cctv",
    category: "CCTV",
    mac: "00:1B:44:33:BB:01",
    ip: "192.168.2.201",
    additionDate: "2024-02-20",
    lastUsageDate: "3 sec ago",
    dataUsage: "62.3 GB",
    online: true,
    blocked: false,
    segment: "office",
    siteId: "SITE-HYD-OFF-007",
    policyId: "OFF_DEVICE_25Mbps_Unlimited_1Device_Monthly",
    location: "Basement Parking",
    registeredBy: "security@techpark.com"
  },
  {
    id: "dev054",
    deviceUserId: "BIO_OFF_001",
    deviceUserName: "Office Entry Biometric",
    name: "ZKTeco SpeedFace V5L",
    type: "digital",
    subtype: "biometric",
    category: "Biometric",
    mac: "00:1B:44:33:BB:02",
    ip: "192.168.2.202",
    additionDate: "2024-02-25",
    lastUsageDate: "45 sec ago",
    dataUsage: "180 MB",
    online: true,
    blocked: false,
    segment: "office",
    siteId: "SITE-HYD-OFF-007",
    policyId: "OFF_DEVICE_25Mbps_Unlimited_1Device_Monthly",
    location: "Main Office Entrance",
    registeredBy: "admin@techpark.com"
  },
  {
    id: "dev055",
    deviceUserId: "PRN_OFF_001",
    deviceUserName: "Central Printer",
    name: "Canon imageRUNNER C3530i",
    type: "digital",
    subtype: "printer",
    category: "Printer",
    mac: "00:1B:44:33:BB:03",
    ip: "192.168.2.203",
    additionDate: "2024-03-10",
    lastUsageDate: "12 min ago",
    dataUsage: "2.4 GB",
    online: true,
    blocked: false,
    segment: "office",
    siteId: "SITE-HYD-OFF-007",
    policyId: "OFF_DEVICE_25Mbps_Unlimited_1Device_Monthly",
    location: "Document Center",
    registeredBy: "admin@techpark.com"
  },
  {
    id: "dev056",
    deviceUserId: "DVR_OFF_001",
    deviceUserName: "Security NVR",
    name: "Uniview NVR304-32E",
    type: "digital",
    subtype: "dvr",
    category: "DVR",
    mac: "00:1B:44:33:BB:04",
    ip: "192.168.2.204",
    additionDate: "2024-02-20",
    lastUsageDate: "1 sec ago",
    dataUsage: "245.6 GB",
    online: true,
    blocked: false,
    segment: "office",
    siteId: "SITE-HYD-OFF-007",
    policyId: "OFF_DEVICE_25Mbps_Unlimited_1Device_Monthly",
    location: "Security Office",
    registeredBy: "security@techpark.com"
  },
  {
    id: "dev082",
    deviceUserId: "TV_OFF_001",
    deviceUserName: "Conference Room TV",
    name: "Samsung 75\" Smart TV",
    type: "digital",
    subtype: "smart_tv",
    category: "Smart TV",
    mac: "00:1B:44:33:BB:05",
    ip: "192.168.2.205",
    additionDate: "2024-03-15",
    lastUsageDate: "45 min ago",
    dataUsage: "8.5 GB",
    online: false,
    blocked: false,
    segment: "office",
    siteId: "SITE-HYD-OFF-007",
    policyId: "OFF_DEVICE_25Mbps_Unlimited_1Device_Monthly",
    location: "Conference Room A",
    registeredBy: "admin@techpark.com"
  },
  {
    id: "dev083",
    deviceUserId: "IOT_OFF_001",
    deviceUserName: "Smart Thermostat",
    name: "Nest Learning Thermostat",
    type: "digital",
    subtype: "iot",
    category: "IoT Device",
    mac: "00:1B:44:33:BB:06",
    ip: "192.168.2.206",
    additionDate: "2024-03-20",
    lastUsageDate: "5 min ago",
    dataUsage: "45 MB",
    online: true,
    blocked: false,
    segment: "office",
    siteId: "SITE-HYD-OFF-007",
    policyId: "OFF_DEVICE_25Mbps_Unlimited_1Device_Monthly",
    location: "Main Office Area",
    registeredBy: "facilities@techpark.com"
  },
  {
    id: "dev084",
    deviceUserId: "ACC_OFF_001",
    deviceUserName: "Server Room Access",
    name: "Kisi Pro Access Reader",
    type: "digital",
    subtype: "access_control",
    category: "Access Control",
    mac: "00:1B:44:33:BB:07",
    ip: "192.168.2.207",
    additionDate: "2024-03-25",
    lastUsageDate: "2 min ago",
    dataUsage: "55 MB",
    online: true,
    blocked: false,
    segment: "office",
    siteId: "SITE-HYD-OFF-007",
    policyId: "OFF_DEVICE_25Mbps_Unlimited_1Device_Monthly",
    location: "Server Room",
    registeredBy: "it@techpark.com"
  },
  {
    id: "dev085",
    deviceUserId: "INT_OFF_001",
    deviceUserName: "Reception Intercom",
    name: "Yealink T54W IP Phone",
    type: "digital",
    subtype: "intercom",
    category: "Intercom",
    mac: "00:1B:44:33:BB:08",
    ip: "192.168.2.208",
    additionDate: "2024-04-01",
    lastUsageDate: "15 min ago",
    dataUsage: "95 MB",
    online: true,
    blocked: false,
    segment: "office",
    siteId: "SITE-HYD-OFF-007",
    policyId: "OFF_DEVICE_25Mbps_Unlimited_1Device_Monthly",
    location: "Reception Desk",
    registeredBy: "admin@techpark.com"
  },
  {
    id: "dev086",
    deviceUserId: "DIS_OFF_001",
    deviceUserName: "Meeting Room Display",
    name: "LG 43\" Digital Signage",
    type: "digital",
    subtype: "display",
    category: "Digital Display",
    mac: "00:1B:44:33:BB:09",
    ip: "192.168.2.209",
    additionDate: "2024-04-05",
    lastUsageDate: "30 min ago",
    dataUsage: "2.8 GB",
    online: true,
    blocked: false,
    segment: "office",
    siteId: "SITE-HYD-OFF-007",
    policyId: "OFF_DEVICE_25Mbps_Unlimited_1Device_Monthly",
    location: "Meeting Room B",
    registeredBy: "admin@techpark.com"
  },

  // =====================
  // CoWorking Digital Devices (WorkHub - Pune)
  // =====================
  {
    id: "dev057",
    deviceUserId: "TV_COW_001",
    deviceUserName: "Meeting Room Display",
    name: "LG 65\" Commercial Display",
    type: "digital",
    subtype: "smart_tv",
    category: "Smart TV",
    mac: "00:1B:44:33:CC:01",
    ip: "192.168.6.201",
    additionDate: "2024-03-15",
    lastUsageDate: "1 hour ago",
    dataUsage: "8.2 GB",
    online: false,
    blocked: false,
    segment: "coWorking",
    siteId: "SITE-PUN-COW-003",
    policyId: "COW_DEVICE_20Mbps_Unlimited_1Device_Daily",
    location: "Meeting Room A",
    registeredBy: "admin@workhub.com"
  },
  {
    id: "dev058",
    deviceUserId: "PRN_COW_001",
    deviceUserName: "Shared Printer",
    name: "Brother MFC-L8900CDW",
    type: "digital",
    subtype: "printer",
    category: "Printer",
    mac: "00:1B:44:33:CC:02",
    ip: "192.168.6.202",
    additionDate: "2024-03-20",
    lastUsageDate: "8 min ago",
    dataUsage: "1.5 GB",
    online: true,
    blocked: false,
    segment: "coWorking",
    siteId: "SITE-PUN-COW-003",
    policyId: "COW_DEVICE_20Mbps_Unlimited_1Device_Daily",
    location: "Print Station - Ground Floor",
    registeredBy: "admin@workhub.com"
  },
  {
    id: "dev059",
    deviceUserId: "CCTV_COW_001",
    deviceUserName: "Reception Camera",
    name: "Hikvision DS-2CD2185FWD-I",
    type: "digital",
    subtype: "cctv",
    category: "CCTV",
    mac: "00:1B:44:33:CC:03",
    ip: "192.168.6.203",
    additionDate: "2024-03-25",
    lastUsageDate: "5 sec ago",
    dataUsage: "28.7 GB",
    online: true,
    blocked: false,
    segment: "coWorking",
    siteId: "SITE-PUN-COW-003",
    policyId: "COW_DEVICE_20Mbps_Unlimited_1Device_Daily",
    location: "Reception Area",
    registeredBy: "security@workhub.com"
  },
  {
    id: "dev060",
    deviceUserId: "BIO_COW_001",
    deviceUserName: "Entry Access Control",
    name: "HID iCLASS SE Reader",
    type: "digital",
    subtype: "biometric",
    category: "Biometric",
    mac: "00:1B:44:33:CC:04",
    ip: "192.168.6.204",
    additionDate: "2024-04-01",
    lastUsageDate: "20 sec ago",
    dataUsage: "95 MB",
    online: true,
    blocked: false,
    segment: "coWorking",
    siteId: "SITE-PUN-COW-003",
    policyId: "COW_DEVICE_20Mbps_Unlimited_1Device_Daily",
    location: "Main Entrance",
    registeredBy: "admin@workhub.com"
  },
  {
    id: "dev087",
    deviceUserId: "DVR_COW_001",
    deviceUserName: "Security NVR",
    name: "Dahua NVR4216-16P-4KS2",
    type: "digital",
    subtype: "dvr",
    category: "DVR",
    mac: "00:1B:44:33:CC:05",
    ip: "192.168.6.205",
    additionDate: "2024-04-05",
    lastUsageDate: "2 sec ago",
    dataUsage: "125.4 GB",
    online: true,
    blocked: false,
    segment: "coWorking",
    siteId: "SITE-PUN-COW-003",
    policyId: "COW_DEVICE_20Mbps_Unlimited_1Device_Daily",
    location: "Security Room",
    registeredBy: "security@workhub.com"
  },
  {
    id: "dev088",
    deviceUserId: "ACC_COW_001",
    deviceUserName: "Meeting Room Access",
    name: "Kisi Controller Pro",
    type: "digital",
    subtype: "access_control",
    category: "Access Control",
    mac: "00:1B:44:33:CC:06",
    ip: "192.168.6.206",
    additionDate: "2024-04-10",
    lastUsageDate: "5 min ago",
    dataUsage: "35 MB",
    online: true,
    blocked: false,
    segment: "coWorking",
    siteId: "SITE-PUN-COW-003",
    policyId: "COW_DEVICE_20Mbps_Unlimited_1Device_Daily",
    location: "Meeting Rooms",
    registeredBy: "admin@workhub.com"
  },
  {
    id: "dev089",
    deviceUserId: "DIS_COW_001",
    deviceUserName: "Event Display",
    name: "Samsung 55\" Digital Signage",
    type: "digital",
    subtype: "display",
    category: "Digital Display",
    mac: "00:1B:44:33:CC:07",
    ip: "192.168.6.207",
    additionDate: "2024-04-15",
    lastUsageDate: "10 min ago",
    dataUsage: "3.5 GB",
    online: true,
    blocked: false,
    segment: "coWorking",
    siteId: "SITE-PUN-COW-003",
    policyId: "COW_DEVICE_20Mbps_Unlimited_1Device_Daily",
    location: "Event Space",
    registeredBy: "events@workhub.com"
  }
];

// ============================================
// USER REPORT DATA - API Format Aligned
// ============================================

/**
 * MissingForAPI (Reports):
 * - Real-time session data aggregation
 * - Historical data beyond portal scope
 * - AAA system correlation data
 * 
 * FrontendOnly (Reports):
 * - segment field for filtering
 * - Friendly date/time formats
 * - Computed averages from sessions
 */

export const userReportData = {
  // 90 days of comprehensive user session data (hundreds of sessions)
  "user-session-history": reportGen.generateUserSessions('2024-01-01', 90),

  // 90 days of user data consumption (thousands of records)
  "user-data-consumption": reportGen.generateUserDataConsumption('2024-01-01', 90),
};

// ============================================
// HELPER FUNCTIONS - Preserved
// ============================================

export const getUserReportData = (reportId) => {
  return userReportData[reportId] || null;
};

export const isUserReport = (reportId) => {
  return reportId in userReportData;
};

export const getUserReportIds = () => {
  return Object.keys(userReportData);
};

export const getUserReportDataByUser = (reportId, userId) => {
  const reportData = userReportData[reportId];
  if (!reportData) return null;
  return reportData.filter(item => item.userId === userId);
};

export const getUserReportDataBySegment = (reportId, segment) => {
  const reportData = userReportData[reportId];
  if (!reportData) return null;
  return reportData.filter(item => item.segment === segment);
};

// ============================================
// DEFAULT EXPORT - Preserved
// ============================================

export default {
  users: sampleUsers,
  devices: sampleDevices,
  reportData: userReportData,
  getUserReportData,
  isUserReport,
  getUserReportIds,
  getUserReportDataByUser,
  getUserReportDataBySegment,
  convertUserToAPIFormat
};