// src/utils/accessLevels.js

export const AccessLevels = {
  SITE: "site",
  CLUSTER: "cluster",
  CITY: "city",
  COMPANY: "company",
  GROUP: "group",
};

export const Roles = {
  ADMIN: "admin",
  MANAGER: "manager",
  USER: "user",
  VIEWER: "viewer",
};

/**
 * Permissions Matrix
 *
 * Access Level Hierarchy (highest to lowest):
 * GROUP > COMPANY > CITY > CLUSTER > SITE
 *
 * Role Hierarchy (highest to lowest):
 * ADMIN > MANAGER > USER > VIEWER
 *
 * Higher access levels inherit permissions from lower levels and add more capabilities.
 * Higher roles have more permissions within the same access level.
 */
export const Permissions = {
  // SITE - Lowest access level, single location only
  [AccessLevels.SITE]: {
    [Roles.ADMIN]: {
      canEditUsers: true,
      canViewReports: true,
      canManageDevices: true,
      canManagePolicies: true,
      canViewAnalytics: true,
      canExportData: true,
      canManageSegments: false, // Cannot manage segments at site level
      canViewMultipleSites: false,
      canManageBilling: false,
      canConfigureSystem: false,
      canManageRoles: false,
    },
    [Roles.MANAGER]: {
      canEditUsers: true,
      canViewReports: true,
      canManageDevices: true,
      canManagePolicies: true,
      canViewAnalytics: true,
      canExportData: true,
      canManageSegments: false,
      canViewMultipleSites: false,
      canManageBilling: false,
      canConfigureSystem: false,
      canManageRoles: false,
    },
    [Roles.USER]: {
      canEditUsers: false,
      canViewReports: true,
      canManageDevices: false,
      canManagePolicies: false,
      canViewAnalytics: true,
      canExportData: false,
      canManageSegments: false,
      canViewMultipleSites: false,
      canManageBilling: false,
      canConfigureSystem: false,
      canManageRoles: false,
    },
    [Roles.VIEWER]: {
      canEditUsers: false,
      canViewReports: true,
      canManageDevices: false,
      canManagePolicies: false,
      canViewAnalytics: true,
      canExportData: false,
      canManageSegments: false,
      canViewMultipleSites: false,
      canManageBilling: false,
      canConfigureSystem: false,
      canManageRoles: false,
    },
  },

  // CLUSTER - Multiple related sites (e.g., building or campus)
  [AccessLevels.CLUSTER]: {
    [Roles.ADMIN]: {
      canEditUsers: true,
      canViewReports: true,
      canManageDevices: true,
      canManagePolicies: true,
      canViewAnalytics: true,
      canExportData: true,
      canManageSegments: true,
      canViewMultipleSites: true,
      canManageBilling: false,
      canConfigureSystem: false,
      canManageRoles: false,
    },
    [Roles.MANAGER]: {
      canEditUsers: true,
      canViewReports: true,
      canManageDevices: true,
      canManagePolicies: true,
      canViewAnalytics: true,
      canExportData: true,
      canManageSegments: false,
      canViewMultipleSites: true,
      canManageBilling: false,
      canConfigureSystem: false,
      canManageRoles: false,
    },
    [Roles.USER]: {
      canEditUsers: false,
      canViewReports: true,
      canManageDevices: false,
      canManagePolicies: false,
      canViewAnalytics: true,
      canExportData: true,
      canManageSegments: false,
      canViewMultipleSites: true,
      canManageBilling: false,
      canConfigureSystem: false,
      canManageRoles: false,
    },
    [Roles.VIEWER]: {
      canEditUsers: false,
      canViewReports: true,
      canManageDevices: false,
      canManagePolicies: false,
      canViewAnalytics: true,
      canExportData: false,
      canManageSegments: false,
      canViewMultipleSites: true,
      canManageBilling: false,
      canConfigureSystem: false,
      canManageRoles: false,
    },
  },

  // CITY - All sites within a city
  [AccessLevels.CITY]: {
    [Roles.ADMIN]: {
      canEditUsers: true,
      canViewReports: true,
      canManageDevices: true,
      canManagePolicies: true,
      canViewAnalytics: true,
      canExportData: true,
      canManageSegments: true,
      canViewMultipleSites: true,
      canManageBilling: true,
      canConfigureSystem: false,
      canManageRoles: true,
    },
    [Roles.MANAGER]: {
      canEditUsers: true,
      canViewReports: true,
      canManageDevices: true,
      canManagePolicies: true,
      canViewAnalytics: true,
      canExportData: true,
      canManageSegments: true,
      canViewMultipleSites: true,
      canManageBilling: false,
      canConfigureSystem: false,
      canManageRoles: false,
    },
    [Roles.USER]: {
      canEditUsers: false,
      canViewReports: true,
      canManageDevices: false,
      canManagePolicies: false,
      canViewAnalytics: true,
      canExportData: true,
      canManageSegments: false,
      canViewMultipleSites: true,
      canManageBilling: false,
      canConfigureSystem: false,
      canManageRoles: false,
    },
    [Roles.VIEWER]: {
      canEditUsers: false,
      canViewReports: true,
      canManageDevices: false,
      canManagePolicies: false,
      canViewAnalytics: true,
      canExportData: true,
      canManageSegments: false,
      canViewMultipleSites: true,
      canManageBilling: false,
      canConfigureSystem: false,
      canManageRoles: false,
    },
  },

  // COMPANY - All sites within a company (multiple cities)
  [AccessLevels.COMPANY]: {
    [Roles.ADMIN]: {
      canEditUsers: true,
      canViewReports: true,
      canManageDevices: true,
      canManagePolicies: true,
      canViewAnalytics: true,
      canExportData: true,
      canManageSegments: true,
      canViewMultipleSites: true,
      canManageBilling: true,
      canConfigureSystem: true,
      canManageRoles: true,
    },
    [Roles.MANAGER]: {
      canEditUsers: true,
      canViewReports: true,
      canManageDevices: true,
      canManagePolicies: true,
      canViewAnalytics: true,
      canExportData: true,
      canManageSegments: true,
      canViewMultipleSites: true,
      canManageBilling: true,
      canConfigureSystem: false,
      canManageRoles: false,
    },
    [Roles.USER]: {
      canEditUsers: false,
      canViewReports: true,
      canManageDevices: false,
      canManagePolicies: false,
      canViewAnalytics: true,
      canExportData: true,
      canManageSegments: false,
      canViewMultipleSites: true,
      canManageBilling: false,
      canConfigureSystem: false,
      canManageRoles: false,
    },
    [Roles.VIEWER]: {
      canEditUsers: false,
      canViewReports: true,
      canManageDevices: false,
      canManagePolicies: false,
      canViewAnalytics: true,
      canExportData: true,
      canManageSegments: false,
      canViewMultipleSites: true,
      canManageBilling: false,
      canConfigureSystem: false,
      canManageRoles: false,
    },
  },

  // GROUP - Highest access level, all sites across all companies
  [AccessLevels.GROUP]: {
    [Roles.ADMIN]: {
      canEditUsers: true,
      canViewReports: true,
      canManageDevices: true,
      canManagePolicies: true,
      canViewAnalytics: true,
      canExportData: true,
      canManageSegments: true,
      canViewMultipleSites: true,
      canManageBilling: true,
      canConfigureSystem: true,
      canManageRoles: true,
    },
    [Roles.MANAGER]: {
      canEditUsers: true,
      canViewReports: true,
      canManageDevices: true,
      canManagePolicies: true,
      canViewAnalytics: true,
      canExportData: true,
      canManageSegments: true,
      canViewMultipleSites: true,
      canManageBilling: true,
      canConfigureSystem: false,
      canManageRoles: true,
    },
    [Roles.USER]: {
      canEditUsers: false,
      canViewReports: true,
      canManageDevices: false,
      canManagePolicies: false,
      canViewAnalytics: true,
      canExportData: true,
      canManageSegments: false,
      canViewMultipleSites: true,
      canManageBilling: false,
      canConfigureSystem: false,
      canManageRoles: false,
    },
    [Roles.VIEWER]: {
      canEditUsers: false,
      canViewReports: true,
      canManageDevices: false,
      canManagePolicies: false,
      canViewAnalytics: true,
      canExportData: true,
      canManageSegments: false,
      canViewMultipleSites: true,
      canManageBilling: false,
      canConfigureSystem: false,
      canManageRoles: false,
    },
  },
};